import os
import random

qujian = [228,229,231,232,233,234]

# startx=956
startx=235
zuojige=6
# endx=startx+zuojige-1
endx=240
web_n = 742
authorization ='Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxIiwiVXNlckFjY291bnRJZCI6IjEiLCJOaWNrbmFtZSI6IueUsOS8r-WFiSIsIlJvbGUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImV4cCI6MTc0MzE0ODY0MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MjAwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MjAwIn0.6h33e7GyImY1r-b8buQ5pjMXzo5UR_pMXqCtWW8rshg'

# 保存网站全局配置
headers = {
    'accept': 'application/json, text/plain, */*',
    'accept-language': 'zh-CN,zh;q=0.9',
    'action-name': 'shop-website.save.global-config',
    'authorization': authorization,
    'content-type': 'application/json;charset=UTF-8',
    'origin': 'https://b08-admin.shop6888.com',
    'priority': 'u=1, i',
    'referer': 'https://b08-admin.shop6888.com/',
    'sec-ch-ua': '"Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-site',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
}

# 网站域名信息
web_site_set = {
"964":"https://iiil.fun",  # 小李 老域名   ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
"963":"https://iiic.fun",
"962":"https://iiit.fun",
"961":"https://hhhy.fun",
"960":"https://kkku.fun",
"959":"https://kkkf.fun",
"958":"https://kkko.fun",
"957":"https://gggj.fun",
"956":"https://hhhc.fun",
"955":"https://iiij.fun",
"954":"https://hhhv.fun",
"953":"https://iiib.fun",
"952":"https://iiio.fun",
"951":"https://jjjk.fun",
"950":"https://jjjz.fun",
"949":"https://kkkb.fun",
"948":"https://kkki.fun",
"947":"https://jjjp.fun",
"946":"https://kkkl.fun",
"945":"https://jjjs.fun",
"944":"https://iiie.fun",
"943":"https://hhhq.fun",
"942":"https://hhho.fun",
"941":"https://iiih.fun",
"940":"https://iiig.fun",
"939":"https://jjjn.fun",
"938":"https://iiiw.fun",
"937":"https://jjju.fun",
"936":"https://jjjw.fun",
"935":"https://jjjf.fun",
"934":"https://hhhj.fun",
"933":"https://iiiz.fun",
"932":"https://jjjb.fun",
"931":"https://iiix.fun",
"930":"https://jjjh.fun",
"929":"https://jjjy.fun",
"928":"https://jjjo.fun",
"927":"https://iiiv.fun",
"926":"https://jjjv.fun",
"925":"https://iiiy.fun",
"924":"https://kkkm.fun",
"923":"https://jjjq.fun",
"922":"https://kkka.fun",
"921":"https://kkkg.fun",
"920":"https://kkke.fun",
"919":"https://iiin.fun",
"918":"https://jjje.fun",
"917":"https://jjjg.fun",
"916":"https://jjjm.fun",
"914":"https://jjjr.fun",
"912":"https://llle.shop",
"911":"https://lllu.shop",
"910":"https://llla.shop",
"909":"https://lllm.shop",
"908":"https://mmmd.shop",
"907":"https://kkkx.shop",
"906":"https://llli.shop",
"904":"https://nnnj.shop",
"903":"https://llld.shop",
"902":"https://mmma.shop",
"901":"https://lllj.shop",
"900":"https://jjjp.shop",
"899":"https://jjjc.shop",
"898":"https://llly.shop",
"897":"https://lllf.shop",
"895":"https://lllc.shop", # 小李 老域名   ↑↑↑↑↑↑↑↑↑↑↑↑↑↑

"915":"https://syvio.store",  # 唯一的 没有被封的 域名 四个
"913":"https://zypix.store",
"905":"https://zyxro.store",
"896":"https://mixza.store",

# "964":"https://vixon.store",  # 2025-02-24 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓  这个 大面积 被封 24号和 17号的域名
# "963":"https://yalvo.store",
# "962":"https://firdo.store",
# "961":"https://pimex.store",
# "960":"https://quvix.store",
# "959":"https://wivix.store",
# "958":"https://sygix.store",
# "957":"https://qubera.store",
# "956":"https://kevix.store",
# "955":"https://oryxe.store",
# "954":"https://syvex.store",  # 2025-02-24
# "953":"https://zexum.store",
# "952":"https://wynor.store",
# "951":"https://yuxer.store",
# "950":"https://xirra.store",
# "949":"https://ralvo.store",
# "948":"https://vovox.store",
# "947":"https://zyrex.store",
# "946":"https://tixum.store",
# "945":"https://xivex.store",
# "944":"https://syxon.store",
# "943":"https://uvexi.store",
# "942":"https://givon.store",
# "941":"https://zoryx.store",
# "940":"https://vevol.store",
# "939":"https://tovex.store",
# "938":"https://sivon.store",
# "937":"https://jivex.store",
# "936":"https://nexix.store",
# "935":"https://xelro.store",
# "934":"https://fynor.store",
# "933":"https://daxor.store",
# "932":"https://duvex.store",
# "931":"https://hexum.store",
# "930":"https://koxen.store",
# "929":"https://bynix.store",
# "928":"https://uvixy.store",
# "927":"https://sytox.store",
# "926":"https://kyxon.store",
# "925":"https://xyvon.store", # 2025-02-24 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
# "924":"https://nivro.store", # 2025-02-17 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
# "923":"https://vexol.store",
# "922":"https://zylvo.store",
# "921":"https://pixyo.store",
# "920":"https://zexly.store",
# "919":"https://zifyo.store",
# "918":"https://wovix.store",
# "917":"https://wixio.store",
# "916":"https://zioxy.store",
# "915":"https://syvio.store",
# "914":"https://zzyxo.store",
# "913":"https://zypix.store",
# "912":"https://zexyl.store",
# "911":"https://zixlo.store",
# "910":"https://zlyra.store",
# "909":"https://vexzo.store",
# "908":"https://zyzol.store",
# "907":"https://zymex.store",
# "906":"https://lyzor.store",
# "905":"https://zyxro.store",
# "904":"https://zifro.store",
# "903":"https://vynex.store",
# "902":"https://mixro.store",
# "901":"https://vezlo.store",
# "900":"https://zimro.store",
# "899":"https://zizlo.store",
# "898":"https://wexlo.store",
# "897":"https://zolzo.store",
# "896":"https://mixza.store",
# "895":"https://xyner.store",  # 2025-02-17 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑

"894":"https://exoma.store",  # 2025-02-04 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
"893":"https://mylira.store",
"892":"https://jaton.store",
"891":"https://wiron.store",
"890":"https://kivlo.store",
"889":"https://optro.store",
"888":"https://oztro.store",
"887":"https://xynic.store",
"886":"https://maxix.store",
"885":"https://zetil.store",
"884":"https://olyxa.store",
"883":"https://ruxora.store",
"882":"https://ebira.store",
"881":"https://umira.store",
"880":"https://fyxix.store",
"879":"https://fador.store",
"878":"https://fanix.store",
"877":"https://hikar.store",
"876":"https://ineoza.store",
"875":"https://yvrax.store",
"874":"https://liler.store",
"873":"https://oxlar.store",
"872":"https://rivix.store",
"871":"https://norix.store",
"870":"https://pastr.store",
"869":"https://lykra.store",
"868":"https://zatron.store",
"867":"https://yfoza.store",
"866":"https://xozor.store",
"865":"https://zosix.store",
"864":"https://joxro.store",
"863":"https://husta.store",
"862":"https://wivra.store",
"861":"https://jital.store",
"860":"https://groza.store",
"859":"https://garpa.store",
"858":"https://jonix.store",
"857":"https://jokor.store",
"856":"https://katos.store",
"855":"https://kimoa.store",
"854":"https://zolin.store",
"853":"https://lisoz.store",
"852":"https://olira.store",
"851":"https://zolro.store",
"850":"https://yolis.store",
"849":"https://zikon.store",
"848":"https://juira.store",
"847":"https://huxor.store",
"846":"https://syves.store",
"845":"https://mista.store",
"844":"https://zekir.store",
"843":"https://rasia.store",
"842":"https://xyver.store",
"841":"https://ydira.store",
"840":"https://ypixx.store",
"839":"https://zovla.store",
"838":"https://yelvo.store",
"837":"https://zetar.store",
"836":"https://yerro.store",
"835":"https://yozin.store",
"834":"https://mastra.store",
"833":"https://uniro.store",
"832":"https://vepro.store",
"831":"https://mixtro.store",  # 2025-02-04 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑
"830": "https://vexoma.shop",  # 2025-01-15 发放的
"829": "https://myzora.shop",
"828": "https://hivana.shop",
"827": "https://xynelo.shop",
"826": "https://delira.shop",
"825": "https://terpix.shop",
"824": "https://fyralo.shop",
"823": "https://wytico.shop",
"822": "https://glerix.shop",
"821": "https://fliric.shop",
"820": "https://qavolt.shop",
"819": "https://zimbyte.shop",
"818": "https://pexoro.shop",
"817": "https://nexari.shop",
"816": "https://yliven.shop",
"815": "https://pyvoro.shop",
"814": "https://tixora.shop",
"813": "https://lerivo.shop",
"812": "https://bivira.shop",
"811": "https://nilora.shop",
"810": "https://hexity.shop",
"809": "https://zixana.shop",
"808": "https://xiviro.shop",
"807": "https://jemira.shop",
"806": "https://qerivo.shop",
"805": "https://pykira.shop",
"804": "https://vunexi.shop",
"803": "https://tevoro.shop",
"802": "https://kolira.shop",
"801": "https://venola.shop",
"800": "https://omaxon.shop",
"799": "https://nyvix.shop",
"798": "https://finrex.shop",
"797": "https://riximo.shop",
"796": "https://toriva.shop",
"795": "https://zexuma.shop",
"794": "https://xomix.shop",
"793": "https://plivex.shop",
"792": "https://mikora.shop",
"791": "https://voxita.shop",
"790": "https://ralira.shop",
"789": "https://givaro.shop",
"788": "https://virola.shop",
"787": "https://olygoa.shop",
"786": "https://jixora.shop",
"785": "https://tylomo.shop",
"784": "https://zorico.shop",
"783": "https://zokera.shop",
"782": "https://zixito.shop",
"781": "https://olivix.shop",
"780":"https://zylira.shop",
"779":"https://zolxa.shop",
"778":"https://zivka.shop",
"777":"https://vyzira.shop",
"776":"https://vixara.shop",
"775":"https://zivila.shop",
"774":"https://voxlo.shop",
"773":"https://zilroa.shop",
"772":"https://zymro.shop",
"771":"https://vexxa.shop",
"770":"https://zilra.shop",
"769":"https://pexxa.shop",
"768":"https://zoxro.shop",
"767":"https://zivly.shop",
"766":"https://zyklo.shop",
"765":"https://zixya.shop",
"764":"https://xyrom.shop",
"763":"https://zymra.shop",
"762":"https://zorara.shop",
"761":"https://mexira.shop",
"760":"https://zivroa.shop",
"759":"https://fylara.shop",
"758":"https://zorira.shop",
"757":"https://zivira.shop",
"756":"https://lixora.shop",
"755":"https://voxar.shop",
"754":"https://zymira.shop",
"753":"https://zixar.shop",
"752":"https://zyvira.shop",
"751":"https://zilira.shop",
"750":"https://vexlor.shop",
"749":"https://zexxa.shop",
"748":"https://zilro.shop",
"747":"https://fyzra.shop",
"746":"https://zirao.shop",
"745":"https://zoxyo.shop",
"744":"https://zifora.shop",
"743":"https://xivira.shop",
"742":"https://zivxa.shop",
"741":"https://zymara.shop",
"740":"https://zaxira.shop",
"739":"https://zoyra.shop",
"738":"https://qixora.shop",
"737":"https://fixar.shop",
"736":"https://zimra.shop",
"735":"https://zyzal.shop",
"734":"https://zivola.shop",
"733":"https://vezro.shop",
"732":"https://zovxa.shop",
"731":"https://zilxa.shop",
"730":"https://nylra.shop",
"729":"https://koyra.shop",
"728":"https://zyzra.shop",
"727":"https://wozzi.shop",

"726":"https://wearx.shop",
"725":"https://chicwear.shop",
"724":"https://chictrnd.shop",
"723":"https://snaptrnd.shop",
"722":"https://trendchic.shop",
"721":"https://gomix.shop",
"720":"https://snapchic.shop",
"719":"https://dressbox.shop",
"718":"https://cartpickz.shop",
"717":"https://fittrd.shop",
"716":"https://fitit.shop",
"715":"https://cartshiftr.shop",
"714":"https://shoppickz.shop",
"713":"https://fashx.shop",
"712":"https://styleit.shop",
"711":"https://styletrnd.shop",
"710":"https://snapmixz.shop",
"709":"https://shopboostz.shop",
"708":"https://fitchic.shop",
"707":"https://fashstyle.shop",
"706":"https://wearsnap.shop",
"705":"https://fitdress.shop",
"704":"https://stylefit.shop",
"703":"https://fashtrd.shop",
"702":"https://wearmix.shop",
"701":"https://weartrnd.shop",
"700":"https://chicit.shop",
"699":"https://cartrite.shop",
"698":"https://snappicksr.shop",
"697":"https://dealflexr.shop",
"696":"https://dealclickr.shop",
"695":"https://buydashr.shop",
"694":"https://shopvibex.shop",
"693":"https://buydashz.shop",
"692":"https://snapboostz.shop",
"691":"https://buyflickr.shop",
"690":"https://dresssnap.shop",
"689":"https://modgo.shop",
"688":"https://fittrend.shop",
"687":"https://trendtrd.shop",
"686":"https://newfit.shop",
"685":"https://chicsnap.shop",
"684":"https://fashchic.shop",
"683":"https://shoptrd.shop",
"682":"https://stylemix.shop",
"681":"https://shoptrnd.shop",
"680":"https://buyclickz.shop",
"679":"https://fittrnd.shop",
"678":"https://cartquickr.shop",
"677":"https://shopchic.shop",
"676":"https://shoppop.shop",
"675":"https://styletrd.shop",
"674":"https://boxfit.shop",
"673":"https://modsnap.shop",
"672":"https://dressmix.shop",
"671":"https://fastmixz.shop",
"670":"https://fastboostz.shop",
"669":"https://snaptrd.shop",
"668":"https://dealpickr.shop",
"667":"https://snapfit.shop",
"666":"https://shopzoom.shop",
"665":"https://fastflexz.shop",
"664":"https://fitsnap.shop",
"663":"https://snapboost.shop",
"662":"https://gotrnd.shop",
"661":"https://chictrd.shop",
"660":"https://snapquickz.shop",
"659":"https://fashit.shop",
"658":"https://snapclickz.shop",
"657":"https://snaprapid.shop",
"656":"https://snapx.shop",
"655":"https://modtrd.shop",
"654":"https://snappopr.shop",
"653":"https://cartpushr.shop",
"652":"https://cartpush.shop",
"651":"https://weartrd.shop",
"650":"https://shopzingr.shop",
"649":"https://chicsew.shop",
"648":"https://sewtrendy.shop",
"647":"https://urbantales.shop",
"646":"https://luxefabricx.shop",
"645":"https://loomfusion.shop",
"644":"https://elegantloom.shop",
"643":"https://weavevibesx.shop",
"642":"https://freshvibesx.shop",
"641":"https://cozyfit.shop",
"640":"https://modeweaves.shop",
"639":"https://loomfit.shop",
"638":"https://styleknit.shop",
"637":"https://freshloom.shop",
"636":"https://chicloom.shop",
"635":"https://softaura.shop",
"634":"https://luxeknit.shop",
"633":"https://wovenaurax.shop",
"632":"https://loomcraftedx.shop",
"631":"https://tailoredglow.shop",
"630":"https://vividcloth.shop",
"629":"https://couturewave.shop",
"628":"https://trendyseam.shop",
"627":"https://loomtide.shop",
"626":"https://fashionvibex.shop",
"625":"https://tailoredweave.shop",
"624":"https://modevibes.shop",
"623":"https://chiccrafted.shop",
"622":"https://loomglowx.shop",
"621":"https://freshfitx.shop",
"620":"https://softfitx.shop",
"619":"https://threadedstyle.shop",
"618":"https://pureglam.shop",
"617":"https://fabricaura.shop",
"616":"https://freshcloth.shop",
"615":"https://seamtales.shop",
"614":"https://elegantfitx.shop",
"613":"https://urbanrobe.shop",
"612":"https://loomtrends.shop",
"611":"https://coutureknit.shop",
"610":"https://vivawear.shop",
"609":"https://elegantthreadsx.shop",
"608":"https://tailoredvibe.shop",
"607":"https://chiccraftx.shop",
"606":"https://voguecraft.shop",
"605":"https://weavefitx.shop",
"604":"https://urbanfitx.shop",
"603":"https://modeweave.shop",
"602":"https://wovenaura.shop",
"601":"https://freshcottonx.shop",
"600":"https://wovenfinesse.shop",
"599":"https://modecove.shop",
"598":"https://dressmaven.shop",
"597":"https://loomtales.shop",
"596":"https://fabcouture.shop",
"595":"https://dapperchic.shop",
"594":"https://modeglam.shop",
"593":"https://chicline.shop",
"592":"https://weavecrafted.shop",
"591":"https://modeloom.shop",
"590":"https://modenestx.shop",
"589":"https://modecraftx.shop",
"588":"https://sewwear.shop",
"587":"https://tailoredweavex.shop",
"586":"https://purevibex.shop",
"585":"https://freshluxe.shop",
"584":"https://loomtalesx.shop",
"583":"https://coutureflow.shop",
"582":"https://cottonchic.shop",
"581":"https://closetvibe.shop",
"580":"https://fashionroots.shop",
"579":"https://qoqq.shop",
"578":"https://qmqq.shop",
"577":"https://srss.shop",
"576":"https://rqrr.shop",
"575":"https://smss.shop",
"574":"https://rsrr.shop",
"573":"https://rurr.shop",
"572":"https://qnqq.shop",
"571":"https://tbtt.shop",
"570":"https://tztt.shop",
"569":"https://usuu.shop",
"568":"https://uruu.shop",
"567":"https://uquu.shop",
"566":"https://unuu.shop",
"565":"https://tytt.shop",
"564":"https://umuu.shop",
"563":"https://wpww.shop",
"562":"https://qyqq.shop",
"561":"https://pvpp.shop",
"560":"https://qsqq.shop",
"559":"https://qhqq.shop",
"558":"https://rnrr.shop",
"557":"https://rmrr.shop",
"556":"https://pzpp.shop",
"555":"https://qwqq.shop",
"554":"https://rorr.shop",
"553":"https://rcrr.shop",
"552":"https://qaqq.shop",
"551":"https://rprr.shop",
"550":"https://rvrr.shop",
"549":"https://tjtt.shop",
"548":"https://uguu.shop",
"547":"https://tatt.shop",
"546":"https://ufuu.shop",
"545":"https://ueuu.shop",
"544":"https://sdss.shop",
"543":"https://tltt.shop",
"542":"https://twtt.shop",
"541":"https://uluu.shop",
"540":"https://uauu.shop",
"539":"https://uhuu.shop",
"538":"https://rerr.shop",
"537":"https://tctt.shop",
"536":"https://tqtt.shop",
"535":"https://szss.shop",
"534":"https://tstt.shop",
"533":"https://sgss.shop",
"532":"https://rirr.shop",
"531":"https://rhrr.shop",
"530":"https://uiuu.shop",
"529":"https://txtt.shop",
"528":"https://rfrr.shop",
"527":"https://tvtt.shop",
"526":"https://rlrr.shop",
"525":"https://tgtt.shop",
"524":"https://thtt.shop",
"523":"https://uwuu.shop",
"522":"https://shss.shop",
"521":"https://tftt.shop",
"520":"https://uyuu.shop",
"519":"https://cosyshoes.top",
"518":"https://cosy-shoe.top",
"517":"https://cosyshoe.top",
"516":"https://cosy-shoe.shop",
"515":"https://underwearcim.fun",
"514":"https://underwearcc.fun",
"513":"https://underweare.shop",
"512":"https://underwearart.shop",
"511":"https://ddunderwear.fun",
"510":"https://iunderwear.fun",
"509":"https://clothingz.fun",
"508":"https://underwearedu.fun",
"507":"https://myunderwear.top",
"506":"https://myunderwear.store",
"505":"https://myunderwear.site",
"504":"https://myunderwear.fun",
"503":"https://mytopyi.fun",
"502":"https://clotheses.shop",
"501":"https://fashionbar.shop",
"500":"https://fashionbar.fun",
"499":"https://fashionbar.site",
"498":"https://fashionbar.top",
"497":"https://fashionattire.shop",
"496":"https://fashiona.site",
"495":"https://apparelz.fun",
"494":"https://njjn.shop",
"493":"https://obbo.shop",
"492":"https://qnnq.shop",
"491":"https://qjjq.shop",
"490":"https://pjjp.shop",
"489":"https://qddq.shop",
"488":"https://qzzq.shop",
"487":"https://nggn.shop",
"486":"https://pzzp.shop",
"485":"https://nttn.shop",
"484":"https://nhhn.shop",
"483":"https://qccq.shop",
"482":"https://niin.shop",
"481":"https://qmmq.shop",
"480":"https://riir.shop",
"479":"https://nddn.shop",
"478":"https://ljjl.shop",
"477":"https://ojjo.shop",
"476":"https://nccn.shop",
"475":"https://nlln.shop",
"474":"https://mxxm.shop",
"473":"https://mppm.shop",
"472":"https://qhhq.shop",
"471":"https://ruur.shop",
"470":"https://pccp.shop",
"469":"https://bbmb.fun",
"468":"https://yyyi.fun",
"467":"https://yyyn.fun",
"466":"https://bbzb.fun",
"465":"https://bblb.fun",
"464":"https://ccdc.fun",
"463":"https://bbtb.fun",
"462":"https://kkqk.site",
"461":"https://llol.site",
"460":"https://llfl.site",
"459":"https://llel.site",
"458":"https://llul.site",
"457":"https://mmcm.site",
"456":"https://mmrm.site",
"455":"https://kkuk.site",
"454":"https://kkxk.site",
"453":"https://lldl.site",
"452":"https://llhl.site",
"451":"https://llvl.fun",
"450":"https://llul.fun",
"448":"https://fffa.store",
"447":"https://lllq.store",
"446":"https://fffq.store",
"445":"https://dddj.store",
"444":"https://lllu.store",
"443":"https://eeem.store",
"442":"https://mmmq.store",
"441":"https://qqqj.store",
"440":"https://kkkc.store",
"439":"https://rrrk.store",
"438":"https://pppy.store",
"437":"https://ccck.store",
"436":"https://aaag.store",
"435":"https://hhhg.store",
"434":"https://kkkd.store",
"433":"https://jjjg.store",
"432":"https://gggy.store",
"431":"https://oooy.store",
"430":"https://hhhi.store",
"429":"https://rrrz.store",
"428":"https://nnnp.store",
"427":"https://lllf.store",
"426":"https://mmmu.store",
"425":"https://hhho.store",
"424":"https://jjjc.store",
"423":"https://mmmx.store",
"422":"https://iiir.store",
"421":"https://cccb.store",
"420":"https://rrrm.store",
"419":"https://oool.store",
"418":"https://mmmv.store",
"417":"https://rrro.store",
"416":"https://jjjy.store",
"415":"https://ooor.store",
"414":"https://pppe.store",
"413":"https://gggr.store",
"412":"https://pppg.store",
"411":"https://hhhb.store",
"410":"https://pppb.store",
"409":"https://aaao.store",
"408":"https://cccx.store",
"407":"https://mmmh.store",
"406":"https://hhhc.store",
"405":"https://cccj.store",
"404":"https://nnnu.store",
"403":"https://rrrq.store",
"402":"https://kkkt.store",
"401":"https://iiih.store",
"400":"https://oooq.store",
"399":"https://hhhe.store",
"398":"https://qqqn.store",
"397":"https://aaat.store",
"396":"https://kkkl.store",
"395":"https://hhhj.store",
"394":"https://aaak.store",
"393":"https://sssv.store",
"392":"https://llly.store",
"391":"https://gggw.store",
"390":"https://hhhs.store",
"389":"https://dddo.store",
"388":"https://llld.store",
"387":"https://sssn.store",
"386":"https://mmmw.store",
"385":"https://fffb.store",
"384":"https://hhhn.store",
"383":"https://rrra.store",
"382":"https://hhhv.store",
"381":"https://hhhd.store",
"380":"https://nnnf.store",
"379":"https://bbbu.store",
"378":"https://mmmt.store",
"377":"https://eeer.store",
"376":"https://lllt.store",
"375":"https://ccch.store",
"374":"https://jjjv.store",
"373":"https://jjju.store",
"372":"https://dddq.store",
"371":"https://jjja.store",
"370":"https://mmmz.store",
"369":"https://nnnt.store",
"368":"https://jjjt.store",
"367":"https://kkkn.store",
"366":"https://ooom.store",
"365":"https://rrrv.store",
"364":"https://qqqy.store",
"363":"https://pppd.store",
"362":"https://pppv.store",
"361":"https://iiiu.store",
"360":"https://ooob.store",
"359":"https://mmmb.store",
"358":"https://sssb.store",
"357":"https://bbbo.store",
"356":"https://hhhf.store",
"355":"https://cccz.store",
"354":"https://rrrt.store",
"353":"https://ggge.store",
"352":"https://ooov.store",
"351":"https://nnnj.store",
"350":"https://pppc.store",
"349":"https://nnnv.store",
"348":"https://iiil.fun",
"347":"https://iiic.fun",
"346":"https://iiit.fun",
"345":"https://hhhy.fun",
"344":"https://kkku.fun",
"343":"https://kkkf.fun",
"342":"https://kkko.fun",
"341":"https://gggj.fun",
"340":"https://hhhc.fun",
"339":"https://iiij.fun",
"338":"https://hhhv.fun",
"337":"https://iiib.fun",
"336":"https://iiio.fun",
"335":"https://jjjk.fun",
"334":"https://jjjz.fun",
# "333":"https://kkkb.fun",  # 这部分老域名 282--333  --->替换了 895--964   66个被封的域名
# "332":"https://kkki.fun",
# "331":"https://jjjp.fun",
# "330":"https://kkkl.fun",
# "329":"https://jjjs.fun",
# "328":"https://iiie.fun",
# "327":"https://hhhq.fun",
# "326":"https://hhho.fun",
# "325":"https://iiih.fun",
# "324":"https://iiig.fun",
# "323":"https://jjjn.fun",
# "322":"https://iiiw.fun",
# "321":"https://jjju.fun",
# "320":"https://jjjw.fun",
# "319":"https://jjjf.fun",
# "318":"https://hhhj.fun",
# "317":"https://iiiz.fun",
# "316":"https://jjjb.fun",
# "315":"https://iiix.fun",
# "314":"https://jjjh.fun",
# "313":"https://jjjy.fun",
# "312":"https://jjjo.fun",
# "311":"https://iiiv.fun",
# "310":"https://jjjv.fun",
# "309":"https://iiiy.fun",
# "308":"https://kkkm.fun",
# "307":"https://jjjq.fun",
# "306":"https://kkka.fun",
# "305":"https://kkkg.fun",
# "304":"https://kkke.fun",
# "303":"https://iiin.fun",
# "302":"https://jjje.fun",
# "301":"https://jjjg.fun",
# "300":"https://jjjm.fun",
# "299":"https://jjjr.fun",
# "298":"https://llle.shop",
# "297":"https://lllu.shop",
# "296":"https://llla.shop",
# "295":"https://lllm.shop",
# "294":"https://mmmd.shop",
# "293":"https://kkkx.shop",
# "292":"https://llli.shop",
# "291":"https://nnnj.shop",
# "290":"https://llld.shop",
# "289":"https://mmma.shop",
# "288":"https://lllj.shop",
# "286":"https://jjjp.shop",
# "285":"https://jjjc.shop",
# "284":"https://llly.shop",
# "283":"https://lllf.shop",
# "282":"https://lllc.shop",
"281":"https://lllv.shop",  # 106服务器 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ 3/8
"280":"https://nnnm.shop",
"279":"https://llls.shop",
"278":"https://mmmx.shop",
"277":"https://mmmk.shop",

"276":"https://mmmu.shop",  # 2025/3/7 重做
"275":"https://nnnl.shop",
"274":"https://mmmq.shop",
"273":"https://mmml.shop",
"272":"https://nnnk.shop",
"271":"https://nnng.shop",

"270":"https://nnnf.shop",
"269":"https://mmmr.shop",
"268":"https://mmmo.shop",
"267":"https://mmmj.shop",
"266":"https://cccr.shop",
"265":"https://bbbv.shop",

"264":"https://aaaq.shop",
"263":"https://aaat.shop",
"262":"https://aaav.shop",
"261":"https://bbbl.shop",
"260":"https://bbbp.shop",
"259":"https://cccz.shop",

"258":"https://cccd.shop",
"257":"https://ccct.shop",
"256":"https://ccch.shop",
"255":"https://bbbf.shop",
"249":"https://womenswear.fun",
"248":"https://womens-wear.store",

"247":"https://wearwomens.store",
"246":"https://women-wear.fun",
"245":"https://women-wear.site",
"244":"https://women-coat.store",
"243":"https://coatwomen.store",
"242":"https://womencoat.site",  # 106服务器 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

"240":"https://coatwear.store", # 90服务器 ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
"239":"https://coatwear.shop",
"238":"https://coatwear.fun",
"237":"https://coatwear.top",
"236":"https://jacketwear.store",
"235":"https://jacketwear.shop",

"234":"https://fashionattire.site",
"233":"https://apparelinfo.store",
"232":"https://fashioncoat.shop",
"231":"https://fashioncoat.store",
"229":"https://fashioncoat.top",
"228":"https://clothesme.store",

"227":"https://topcoat.fun",  # 2025-03-11 星期二
"226":"https://coatcs.fun",
"225":"https://womencoat.store",
"224":"https://womencoat.shop",
"223":"https://womencoat.top",
"222":"https://womencoat.fun",

"221":"https://clothingmei.fun",  # 2025-03-10
"220":"https://jacketa.fun",
"219":"https://jacketcc.shop",
"218":"https://clothingda.shop",
"217":"https://clothingkj.fun",
"216":"https://ccclothing.fun",  # 90服务器 ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑
}

# 标题
baioti_set = [
"Women's Oversized Hoodies & Sweatshirts - Cozy Fleece-Lined Pullover for Casual Comfort and Style.",
"Trendy Women's Graphic Print Hoodies & Sweatshirts - Soft Cotton Blend for Everyday Wear.",
"Women's Cropped Hoodies & Sweatshirts - Stylish and Comfortable for Gym or Lounge Outfits.",
"Women's Zip-Up Hoodies & Sweatshirts - Lightweight and Breathable for Spring or Fall Layering.",
"Women's Hoodies & Sweatshirts with Thumbholes - Perfect for Running, Yoga, or Outdoor Activities.",
"Women's Fleece-Lined Hoodies & Sweatshirts - Warm and Cozy for Winter Comfort and Style.",
"Women's Hoodies & Sweatshirts with Drawstring Hood - Soft and Stylish for Casual Everyday Look.",
"Women's Thermal Hoodies & Sweatshirts - Heavyweight Fabric for Cold Weather and Outdoor Adventures.",
"Women's Hoodies & Sweatshirts with Kangaroo Pocket - Functional and Fashionable for Errands or Relaxing.",
"Women's Hoodies & Sweatshirts with Embroidered Designs - Unique and Chic for a Personalized Look.",
"Women's Lightweight Jackets for Spring - Waterproof and Windproof for Outdoor Adventures and Travel.",
"Women's Faux Leather Jackets - Stylish and Durable for Night Out or Casual Everyday Wear.",
"Women's Puffer Jackets for Winter - Warm and Insulated for Extreme Cold Weather and Snow Days.",
"Women's Denim Jackets with Distressed Look - Perfect for Layering in Spring or Fall Outfits.",
"Women's Bomber Jackets with Ribbed Hem - Trendy and Comfortable for a Sporty Chic Style.",
"Women's Trench Coats - Classic and Elegant for Office Wear or Formal Occasions.",
"Women's Parkas with Fur Hood - Warm and Stylish for Winter Outdoor Activities and Commutes.",
"Women's Windbreakers - Lightweight and Breathable for Running, Hiking, or Casual Weekend Outings.",
"Women's Blazers with Structured Fit - Perfect for Office Wear or Smart Casual Events.",
"Women's Raincoats with Hood - Waterproof and Functional for Spring Showers or Outdoor Adventures.",
"Women's Chunky Knit Sweaters - Cozy and Warm for Winter Comfort and Casual Style.",
"Women's Turtleneck Sweaters - Elegant and Versatile for Office Wear or Layering in Fall.",
"Women's Cashmere Sweaters - Luxuriously Soft and Lightweight for Year-Round Comfort.",
"Women's Oversized Sweaters - Relaxed Fit for a Cozy and Stylish Everyday Look.",
"Women's Cable Knit Sweaters - Classic and Timeless for Winter Outfits and Holiday Gatherings.",
"Women's Cropped Sweaters - Trendy and Perfect for High-Waisted Pants or Skirts.",
"Women's V-Neck Sweaters - Flattering and Versatile for Layering or Standalone Outfits.",
"Women's Cardigan Sweaters - Lightweight and Perfect for Spring or Fall Layering.",
"Women's Sweaters with Embellishments - Unique and Eye-Catching for Special Occasions.",
"Women's Sweaters with Ribbed Details - Stylish and Comfortable for Casual or Dressy Outfits.",
"Women's Basic Cotton T-Shirts - Soft and Comfortable for Everyday Casual Wear.",
"Women's Graphic Print T-Shirts - Trendy and Fun for a Personalized Style Statement.",
"Women's Oversized T-Shirts - Relaxed Fit for a Comfortable and Chic Look.",
"Women's V-Neck T-Shirts - Flattering and Versatile for Layering or Standalone Outfits.",
"Women's Cropped T-Shirts - Stylish and Perfect for High-Waisted Jeans or Skirts.",
"Women's Long-Sleeve T-Shirts - Lightweight and Ideal for Spring or Fall Layering.",
"Women's Striped T-Shirts - Classic and Timeless for a Nautical-Inspired Look.",
"Women's T-Shirts with Embroidery - Unique and Elegant for a Personalized Touch.",
"Women's T-Shirts with Ruffled Sleeves - Feminine and Chic for Casual or Dressy Outfits.",
"Women's T-Shirts with High-Low Hem - Trendy and Perfect for a Modern Style Statement.",
"Women's Silk Blouses - Luxurious and Elegant for Office Wear or Special Occasions.",
"Women's Ruffled Blouses - Feminine and Chic for a Romantic and Stylish Look.",
"Women's Printed Blouses - Trendy and Perfect for Adding a Pop of Color to Your Outfit.",
"Women's Peplum Blouses - Flattering and Versatile for Office Wear or Evening Events.",
"Women's Long-Sleeve Blouses - Lightweight and Ideal for Spring or Fall Layering.",
"Women's Wrap Blouses - Stylish and Comfortable for a Flattering and Feminine Silhouette.",
"Women's Lace Blouses - Delicate and Elegant for a Romantic and Chic Look.",
"Women's Button-Down Blouses - Classic and Perfect for Office Wear or Smart Casual Outfits.",
"Women's Off-Shoulder Blouses - Trendy and Perfect for Summer Parties or Beach Vacations.",
"Women's Blouses with Bow Details - Feminine and Chic for a Playful and Stylish Look.",
"Women's High-Waisted Pants - Flattering and Versatile for Office Wear or Casual Outfits.",
"Women's Wide-Leg Pants - Trendy and Comfortable for a Chic and Modern Look.",
"Women's Skinny Pants - Slim-Fit and Perfect for Pairing with Blouses or Sweaters.",
"Women's Cropped Pants - Stylish and Ideal for Spring or Summer Outfits.",
"Women's Palazzo Pants - Flowy and Comfortable for a Bohemian-Inspired Look.",
"Women's Leather Pants - Edgy and Stylish for Night Out or Evening Events.",
"Women's Jogger Pants - Comfortable and Perfect for Casual Wear or Lounging at Home.",
"Women's Tailored Pants - Structured and Elegant for Office Wear or Formal Occasions.",
"Women's Paperbag Waist Pants - Trendy and Perfect for a Fashion-Forward Look.",
"Women's Linen Pants - Lightweight and Breathable for Summer Comfort and Style.",
"Women's High-Waisted Jeans - Flattering and Versatile for Casual or Dressy Outfits.",
"Women's Skinny Jeans - Slim-Fit and Perfect for Pairing with Blouses or T-Shirts.",
"Women's Boyfriend Jeans - Relaxed Fit for a Comfortable and Chic Look.",
"Women's Mom Jeans - Retro-Inspired and Trendy for a Vintage Style Statement.",
"Women's Flared Jeans - 70s-Inspired and Perfect for a Bohemian Chic Look.",
"Women's Distressed Jeans - Edgy and Stylish for a Casual and Cool Outfit.",
"Women's Cropped Jeans - Trendy and Ideal for Spring or Summer Outfits.",
"Women's Black Jeans - Classic and Versatile for Day-to-Night Transition.",
"Women's White Jeans - Fresh and Perfect for Summer or Spring Outfits.",
"Women's Stretch Jeans - Comfortable and Flexible for All-Day Wear.",
"Women's Midi Skirts - Elegant and Versatile for Office Wear or Special Occasions.",
"Women's Mini Skirts - Trendy and Perfect for a Fun and Flirty Look.",
"Women's Pleated Skirts - Feminine and Chic for a Romantic and Stylish Outfit.",
"Women's Denim Skirts - Casual and Perfect for Pairing with T-Shirts or Blouses.",
"Women's Leather Skirts - Edgy and Stylish for Night Out or Evening Events.",
"Women's Wrap Skirts - Flattering and Comfortable for a Feminine Silhouette.",
"Women's High-Waisted Skirts - Trendy and Perfect for Tucking in Blouses or Sweaters.",
"Women's A-Line Skirts - Classic and Timeless for a Flattering and Elegant Look.",
"Women's Maxi Skirts - Flowy and Perfect for Summer or Beach Vacations.",
"Women's Pencil Skirts - Structured and Elegant for Office Wear or Formal Events.",
"Women's Floral Mini Dresses - Feminine and Perfect for Spring or Summer Outfits.",
"Women's Bodycon Mini Dresses - Sleek and Stylish for Night Out or Parties.",
"Women's Lace Mini Dresses - Delicate and Elegant for a Romantic and Chic Look.",
"Women's Denim Mini Dresses - Casual and Perfect for Daytime Outings or Errands.",
"Women's Off-Shoulder Mini Dresses - Trendy and Ideal for Summer Parties or Vacations.",
"Women's Slip Mini Dresses - Minimalist and Chic for a Modern Style Statement.",
"Women's Ruffled Mini Dresses - Playful and Feminine for a Fun and Flirty Look.",
"Women's Wrap Mini Dresses - Flattering and Comfortable for a Feminine Silhouette.",
"Women's Shirt Mini Dresses - Casual and Perfect for Layering with Boots or Sneakers.",
"Women's Sequin Mini Dresses - Glamorous and Perfect for Evening Events or Parties.",
"Women's Floral Maxi Dresses - Feminine and Perfect for Spring or Summer Outfits.",
"Women's Boho Maxi Dresses - Flowy and Comfortable for a Bohemian-Inspired Look.",
"Women's Lace Maxi Dresses - Delicate and Elegant for a Romantic and Chic Style.",
"Women's Wrap Maxi Dresses - Flattering and Perfect for a Feminine Silhouette.",
"Women's Slit Maxi Dresses - Trendy and Stylish for Evening Events or Parties.",
"Women's Off-Shoulder Maxi Dresses - Perfect for Summer Vacations or Beach Weddings.",
"Women's Chiffon Maxi Dresses - Lightweight and Ideal for Spring or Summer Outfits.",
"Women's Tiered Maxi Dresses - Playful and Feminine for a Fun and Flirty Look.",
"Women's Halter Maxi Dresses - Stylish and Perfect for Summer Parties or Beach Outings.",
"Women's Embellished Maxi Dresses - Glamorous and Ideal for Formal Events or Weddings.",
]

# 描述
miaoshu_set = [
"Stay cozy and stylish with our oversized hoodies and sweatshirts, made from soft fleece-lined fabric for ultimate comfort.",
"Explore the outdoors in comfort with our lightweight jackets, designed to be waterproof and windproof for spring adventures.",
"Elevate your athleisure wardrobe with cropped hoodies and sweatshirts, perfect for the gym or lounging at home.",
"Add an edgy touch to your outfit with faux leather jackets, durable and stylish for a night out or casual wear.",
"Layer up in style with zip-up hoodies and sweatshirts, lightweight and breathable for transitional weather.",
"Brave the cold in style with puffer jackets, insulated and warm for winter adventures or daily commutes.",
"Stay active and comfortable with hoodies and sweatshirts featuring thumbholes, ideal for running or yoga.",
"Add a trendy touch to your wardrobe with distressed denim jackets, perfect for layering in spring or fall.",
"Stay cozy all winter long with fleece-lined hoodies and sweatshirts, soft and warm for cold days.",
"Achieve a sporty chic look with bomber jackets, featuring a ribbed hem for trendy everyday wear.",
"Wrap yourself in luxury with chunky knit sweaters, cozy and warm for winter comfort.",
"Stay stylish and comfortable with basic cotton T-shirts, perfect for everyday casual wear.",
"Add a pop of color to your outfit with printed blouses, trendy and versatile for any occasion.",
"Flatter your figure with high-waisted pants, perfect for office wear or casual outings.",
"Step out in style with midi skirts, elegant and versatile for work or special occasions.",
"Make a statement with floral mini dresses, feminine and perfect for spring or summer.",
"Stay cool and chic in maxi dresses, flowy and comfortable for summer vacations.",
"Upgrade your wardrobe with turtleneck sweaters, elegant and perfect for layering in fall.",
"Add a playful touch to your look with graphic print T-shirts, fun and trendy for casual wear.",
"Stay warm and stylish in thermal hoodies, heavyweight fabric for cold weather.",
"Achieve a polished look with tailored pants, structured and elegant for office wear.",
"Add a romantic touch to your outfit with lace blouses, delicate and perfect for special occasions.",
"Stay comfortable and stylish in jogger pants, perfect for casual wear or lounging at home.",
"Make a bold statement with leather skirts, edgy and stylish for night out or evening events.",
"Stay cozy and chic in cable knit sweaters, classic and timeless for winter outfits.",
"Add a nautical vibe to your wardrobe with striped T-shirts, perfect for a casual summer look.",
"Stay warm and trendy in parkas with fur hood, ideal for winter outdoor activities.",
"Flatter your silhouette with wrap blouses, stylish and comfortable for a feminine look.",
"Stay comfortable and stylish in wide-leg pants, trendy and perfect for a modern look.",
"Add a bohemian touch to your outfit with palazzo pants, flowy and comfortable for summer.",
"Stay cozy and chic in cropped sweaters, perfect for pairing with high-waisted pants or skirts.",
"Add a pop of personality to your look with embroidered T-shirts, unique and eye-catching.",
"Stay warm and stylish in thermal jackets, perfect for winter outdoor adventures.",
"Achieve a flirty look with mini skirts, trendy and perfect for a fun night out.",
"Stay comfortable and chic in linen pants, lightweight and breathable for summer.",
"Add a touch of elegance to your outfit with silk blouses, luxurious and perfect for formal events.",
"Stay cozy and stylish in oversized sweaters, perfect for a relaxed and chic look.",
"Add a playful touch to your wardrobe with ruffled blouses, feminine and perfect for spring.",
"Stay warm and trendy in puffer vests, perfect for layering in winter.",
"Achieve a sleek look with skinny jeans, slim-fit and perfect for pairing with blouses or T-shirts.",
"Add a romantic touch to your outfit with lace mini dresses, delicate and perfect for date nights.",
"Stay comfortable and stylish in boyfriend jeans, relaxed fit for a casual look.",
"Add a vintage vibe to your wardrobe with mom jeans, retro-inspired and trendy.",
"Stay cozy and chic in cashmere sweaters, luxuriously soft for year-round comfort.",
"Add a modern touch to your look with off-shoulder blouses, trendy and perfect for summer.",
"Stay warm and stylish in wool coats, perfect for winter commutes or formal events.",
"Achieve a flirty look with bodycon mini dresses, sleek and perfect for parties.",
"Stay comfortable and chic in paperbag waist pants, trendy and perfect for a fashion-forward look.",
"Add a pop of color to your outfit with floral maxi dresses, perfect for summer vacations.",
"Stay cozy and stylish in thermal leggings, perfect for layering in winter.",
"Add a playful touch to your look with sequin mini dresses, glamorous and perfect for evening events.",
"Stay comfortable and chic in linen blouses, lightweight and breathable for summer.",
"Achieve a polished look with pencil skirts, structured and elegant for office wear.",
"Add a romantic touch to your outfit with ruffled mini dresses, feminine and perfect for spring.",
"Stay cozy and stylish in fleece-lined leggings, perfect for winter comfort.",
"Add a modern touch to your look with slit maxi dresses, trendy and perfect for evening events.",
"Stay comfortable and chic in denim skirts, casual and perfect for pairing with T-shirts.",
"Achieve a flirty look with off-shoulder mini dresses, perfect for summer parties.",
"Add a pop of personality to your outfit with graphic sweatshirts, fun and trendy for casual wear.",
"Stay cozy and stylish in thermal tops, perfect for layering in winter.",
"Add a romantic touch to your outfit with lace maxi dresses, delicate and perfect for weddings.",
"Stay comfortable and chic in jogger skirts, perfect for casual outings or running errands.",
"Achieve a sleek look with leather pants, edgy and perfect for night out.",
"Add a playful touch to your wardrobe with tiered maxi dresses, flowy and perfect for summer.",
"Stay cozy and stylish in sherpa jackets, warm and perfect for winter.",
"Add a modern touch to your look with wrap mini dresses, flattering and perfect for date nights.",
"Stay comfortable and chic in cargo pants, trendy and perfect for casual wear.",
"Achieve a flirty look with halter mini dresses, perfect for summer parties.",
"Add a pop of color to your outfit with printed maxi dresses, perfect for beach vacations.",
"Stay cozy and stylish in quilted jackets, warm and perfect for winter.",
"Add a romantic touch to your outfit with chiffon blouses, lightweight and perfect for spring.",
"Stay comfortable and chic in culottes, trendy and perfect for office wear.",
"Achieve a sleek look with tailored blazers, structured and perfect for formal events.",
"Add a playful touch to your look with embellished mini dresses, perfect for evening events.",
"Stay cozy and stylish in thermal scarves, perfect for winter layering.",
"Add a modern touch to your wardrobe with asymmetrical skirts, trendy and perfect for a unique look.",
"Stay comfortable and chic in knit dresses, cozy and perfect for winter.",
"Achieve a flirty look with wrap skirts, flattering and perfect for a feminine silhouette.",
"Add a pop of personality to your outfit with embroidered blouses, unique and perfect for special occasions.",
"Stay cozy and stylish in fleece jackets, warm and perfect for winter.",
"Add a romantic touch to your outfit with satin mini dresses, luxurious and perfect for evening events.",
"Stay comfortable and chic in high-waisted shorts, trendy and perfect for summer.",
"Achieve a sleek look with tailored coats, structured and perfect for winter.",
"Add a playful touch to your wardrobe with tiered skirts, flowy and perfect for spring.",
"Stay cozy and stylish in thermal gloves, perfect for winter outdoor activities.",
"Add a modern touch to your look with slip dresses, minimalist and perfect for evening events.",
"Stay comfortable and chic in wide-brim hats, perfect for summer vacations.",
"Achieve a flirty look with off-shoulder maxi dresses, perfect for beach weddings.",
"Add a pop of color to your outfit with printed skirts, trendy and perfect for spring.",
"Stay cozy and stylish in knit scarves, perfect for winter layering.",
"Add a romantic touch to your outfit with velvet dresses, luxurious and perfect for holiday parties.",
"Stay comfortable and chic in platform sneakers, trendy and perfect for casual wear.",
"Achieve a sleek look with tailored jumpsuits, structured and perfect for formal events.",
"Add a playful touch to your wardrobe with sequin blouses, glamorous and perfect for evening events.",
"Stay cozy and stylish in quilted vests, warm and perfect for winter.",
"Add a modern touch to your look with asymmetrical dresses, trendy and perfect for a unique style.",
"Stay comfortable and chic in knit cardigans, cozy and perfect for layering.",
"Achieve a flirty look with ruffled maxi dresses, feminine and perfect for summer.",
"Add a pop of personality to your outfit with graphic hoodies, fun and trendy for casual wear.",
"Stay cozy and stylish in thermal socks, perfect for winter comfort.",
]

# 关键词
guanjianci_set = [
"Women's oversized hoodies, cozy fleece-lined sweatshirts, lightweight jackets, floral mini dresses, high-waisted jeans, trendy blouses, cable knit sweaters, casual T-shirts, midi skirts, maxi dresses, winter puffer jackets, summer linen pants, off-shoulder tops, leather skirts, cropped sweaters, graphic print hoodies, denim jackets, wrap dresses, jogger pants, thermal leggings, lace blouses, wide-leg trousers, bodycon dresses, bomber jackets, pleated skirts, turtleneck sweaters, distressed jeans, chiffon blouses, paperbag waist pants, sequin mini dresses, parkas, slip dresses, cargo pants, halter tops, quilted vests",
"Women's cropped hoodies, zip-up sweatshirts, faux leather jackets, floral maxi dresses, skinny jeans, ruffled blouses, chunky knit sweaters, basic cotton T-shirts, A-line skirts, boho maxi dresses, winter parkas, summer palazzo pants, off-shoulder blouses, leather pants, oversized sweaters, graphic T-shirts, denim skirts, wrap blouses, wide-leg jeans, thermal tops, lace mini dresses, tailored pants, bodycon skirts, bomber vests, pleated midi skirts, cashmere sweaters, mom jeans, silk blouses, high-waisted trousers, sequin maxi dresses, puffer vests, slip skirts, cargo shorts, halter dresses, quilted jackets",
"Women's fleece-lined hoodies, thermal sweatshirts, trench coats, floral mini skirts, high-waisted pants, printed blouses, wool sweaters, striped T-shirts, pencil skirts, tiered maxi dresses, winter wool coats, summer culottes, off-shoulder dresses, faux leather skirts, cropped cardigans, graphic sweatshirts, distressed denim jackets, wrap skirts, jogger shorts, thermal jackets, lace maxi dresses, wide-leg culottes, bodycon tops, quilted bombers, pleated mini skirts, turtleneck tops, boyfriend jeans, chiffon tops, paperbag shorts, sequin blouses, parka coats, slip tops, cargo skirts, halter necklines, quilted parkas",
"Women's oversized sweatshirts, cozy pullover hoodies, lightweight parkas, floral midi dresses, skinny pants, ruffled tops, cable knit cardigans, basic V-neck T-shirts, A-line mini skirts, boho slip dresses, winter puffer vests, summer linen skirts, off-shoulder sweaters, leather jackets, cropped hoodies, graphic print T-shirts, denim overalls, wrap tops, wide-leg trousers, thermal tights, lace camisoles, tailored blazers, bodycon jumpsuits, bomber jackets, pleated palazzo pants, cashmere cardigans, mom shorts, silk camisoles, high-waisted culottes, sequin tops, puffer coats, slip dresses, cargo pants, halter jumpsuits, quilted blazers",
"Women's zip-up hoodies, fleece-lined jackets, floral maxi skirts, high-waisted shorts, printed tops, wool cardigans, striped long-sleeve T-shirts, pencil pants, tiered mini dresses, winter trench coats, summer wide-leg pants, off-shoulder tops, faux leather pants, oversized cardigans, graphic hoodies, distressed jeans, wrap dresses, jogger skirts, thermal shirts, lace tops, wide-leg jumpsuits, bodycon mini dresses, quilted vests, pleated trousers, turtleneck dresses, boyfriend shorts, chiffon blouses, paperbag pants, sequin skirts, parka jackets, slip skirts, cargo jumpsuits, halter tops, quilted coats",
"Women's thermal hoodies, cozy pullover jackets, floral mini dresses, skinny jeans, ruffled blouses, chunky knit cardigans, basic crewneck T-shirts, A-line midi skirts, boho maxi dresses, winter parkas, summer linen pants, off-shoulder blouses, leather skirts, cropped sweatshirts, graphic print tops, denim jackets, wrap skirts, jogger pants, thermal leggings, lace dresses, wide-leg trousers, bodycon tops, bomber vests, pleated skirts, cashmere sweaters, mom jeans, silk tops, high-waisted pants, sequin dresses, puffer jackets, slip tops, cargo shorts, halter necklines, quilted bombers",
"Women's oversized pullovers, fleece-lined sweatshirts, lightweight trench coats, floral maxi dresses, high-waisted jeans, printed blouses, wool sweaters, striped T-shirts, pencil skirts, tiered mini dresses, winter wool jackets, summer culottes, off-shoulder dresses, faux leather pants, cropped hoodies, graphic sweatshirts, distressed denim skirts, wrap tops, wide-leg jeans, thermal jackets, lace blouses, tailored pants, bodycon dresses, quilted bombers, pleated midi skirts, turtleneck sweaters, boyfriend jeans, chiffon tops, paperbag waist pants, sequin tops, parka coats, slip dresses, cargo skirts, halter jumpsuits, quilted parkas",
"Women's cropped sweatshirts, zip-up hoodies, faux leather jackets, floral mini skirts, skinny pants, ruffled tops, cable knit sweaters, basic T-shirts, A-line skirts, boho maxi dresses, winter puffer vests, summer linen pants, off-shoulder blouses, leather skirts, oversized sweaters, graphic print T-shirts, denim jackets, wrap dresses, jogger pants, thermal leggings, lace tops, wide-leg trousers, bodycon skirts, bomber jackets, pleated mini skirts, cashmere cardigans, mom jeans, silk blouses, high-waisted trousers, sequin dresses, puffer coats, slip skirts, cargo pants, halter tops, quilted jackets",
"Women's fleece-lined pullovers, thermal sweatshirts, trench coats, floral midi dresses, high-waisted shorts, printed blouses, wool cardigans, striped long-sleeve T-shirts, pencil pants, tiered maxi dresses, winter parkas, summer wide-leg pants, off-shoulder tops, faux leather skirts, cropped hoodies, graphic sweatshirts, distressed jeans, wrap skirts, jogger shorts, thermal tops, lace dresses, wide-leg jumpsuits, bodycon mini dresses, quilted vests, pleated trousers, turtleneck sweaters, boyfriend shorts, chiffon blouses, paperbag pants, sequin tops, parka jackets, slip dresses, cargo jumpsuits, halter necklines, quilted coats",
"Women's oversized hoodies, cozy fleece-lined jackets, floral mini dresses, skinny jeans, ruffled blouses, chunky knit sweaters, basic cotton T-shirts, midi skirts, maxi dresses, winter puffer jackets, summer linen pants, off-shoulder tops, leather skirts, cropped sweaters, graphic print hoodies, denim jackets, wrap dresses, jogger pants, thermal leggings, lace blouses, wide-leg trousers, bodycon dresses, bomber jackets, pleated skirts, turtleneck sweaters, distressed jeans, chiffon blouses, paperbag waist pants, sequin mini dresses, parkas, slip dresses, cargo pants, halter tops, quilted vests",
"Women's cropped hoodies, zip-up sweatshirts, lightweight jackets, floral maxi dresses, high-waisted jeans, printed blouses, cable knit sweaters, basic T-shirts, A-line skirts, boho maxi dresses, winter parkas, summer linen pants, off-shoulder tops, leather skirts, oversized sweaters, graphic print T-shirts, denim jackets, wrap dresses, jogger pants, thermal leggings, lace blouses, wide-leg trousers, bodycon dresses, bomber jackets, pleated skirts, turtleneck sweaters, distressed jeans, chiffon blouses, paperbag waist pants, sequin mini dresses, puffer coats, slip dresses, cargo pants, halter tops, quilted vests",
"Women's fleece-lined hoodies, thermal sweatshirts, trench coats, floral mini dresses, skinny jeans, ruffled blouses, wool sweaters, striped T-shirts, pencil skirts, tiered maxi dresses, winter wool coats, summer culottes, off-shoulder dresses, faux leather skirts, cropped cardigans, graphic sweatshirts, distressed denim jackets, wrap skirts, jogger shorts, thermal jackets, lace maxi dresses, wide-leg culottes, bodycon tops, quilted bombers, pleated mini skirts, turtleneck tops, boyfriend jeans, chiffon tops, paperbag shorts, sequin blouses, parka coats, slip tops, cargo skirts, halter necklines, quilted parkas",
"Women's cropped sweatshirts, zip-up hoodies, faux leather jackets, floral mini skirts, skinny pants, ruffled tops, cable knit sweaters, basic T-shirts, A-line skirts, boho maxi dresses, winter puffer vests, summer linen pants, off-shoulder blouses, leather skirts, oversized sweaters, graphic print T-shirts, denim jackets, wrap dresses, jogger pants, thermal leggings, lace tops, wide-leg trousers, bodycon skirts, bomber jackets, pleated mini skirts",
"Oversized hoodies, floral mini dresses, high-waisted jeans, printed blouses, cable knit sweaters, basic T-shirts, A-line skirts, boho maxi dresses, winter parkas, summer linen pants, off-shoulder tops, leather skirts, cropped sweaters, graphic print hoodies, denim jackets, wrap dresses, jogger pants, thermal leggings, lace blouses, wide-leg trousers",
"Fleece-lined hoodies, thermal sweatshirts, trench coats, floral mini dresses, skinny jeans, ruffled blouses, wool sweaters, striped T-shirts, pencil skirts, tiered maxi dresses, winter wool coats, summer culottes, off-shoulder dresses, faux leather skirts, cropped cardigans, graphic sweatshirts, distressed denim jackets, wrap skirts, jogger shorts, thermal jackets",
"Cropped hoodies, zip-up sweatshirts, lightweight jackets, floral maxi dresses, high-waisted jeans, printed blouses, cable knit sweaters, basic T-shirts, A-line skirts, boho maxi dresses, winter parkas, summer linen pants, off-shoulder tops, leather skirts, oversized sweaters, graphic print T-shirts, denim jackets, wrap dresses, jogger pants, thermal leggings",
"Women's oversized hoodies, cozy fleece-lined jackets, floral mini dresses, skinny jeans, ruffled blouses, chunky knit sweaters, basic cotton T-shirts, midi skirts, maxi dresses, winter puffer jackets, summer linen pants, off-shoulder tops, leather skirts, cropped sweaters, graphic print hoodies, denim jackets, wrap dresses, jogger pants, thermal leggings, lace blouses",
"Women's cropped hoodies, zip-up sweatshirts, lightweight jackets, floral maxi dresses, high-waisted jeans, printed blouses, cable knit sweaters, basic T-shirts, A-line skirts, boho maxi dresses, winter parkas, summer linen pants, off-shoulder tops, leather skirts, oversized sweaters, graphic print T-shirts, denim jackets, wrap dresses, jogger pants, thermal leggings",
"Women's fleece-lined hoodies, thermal sweatshirts, trench coats, floral mini dresses, skinny jeans, ruffled blouses, wool sweaters, striped T-shirts, pencil skirts, tiered maxi dresses, winter wool coats, summer culottes, off-shoulder dresses, faux leather skirts, cropped cardigans, graphic sweatshirts, distressed denim jackets, wrap skirts, jogger shorts, thermal jackets",
"Women's oversized sweatshirts, cozy pullover hoodies, lightweight parkas, floral midi dresses, skinny pants, ruffled tops, cable knit cardigans, basic V-neck T-shirts, A-line mini skirts, boho slip dresses, winter puffer vests, summer linen skirts, off-shoulder sweaters, leather jackets, cropped hoodies, graphic print T-shirts, denim overalls, wrap tops, wide-leg trousers, thermal tights",
"Women's zip-up hoodies, fleece-lined jackets, floral maxi skirts, high-waisted shorts, printed tops, wool cardigans, striped long-sleeve T-shirts, pencil pants, tiered mini dresses, winter trench coats, summer wide-leg pants, off-shoulder tops, faux leather pants, oversized cardigans, graphic hoodies, distressed jeans, wrap dresses, jogger skirts, thermal shirts, lace tops",
"Women's thermal hoodies, cozy pullover jackets, floral mini dresses, skinny jeans, ruffled blouses, chunky knit cardigans, basic crewneck T-shirts, A-line midi skirts, boho maxi dresses, winter parkas, summer linen pants, off-shoulder blouses, leather skirts, cropped sweatshirts, graphic print tops, denim jackets, wrap skirts, jogger pants, thermal leggings, lace dresses",
"Women's oversized pullovers, fleece-lined sweatshirts, lightweight trench coats, floral maxi dresses, high-waisted jeans, printed blouses, wool sweaters, striped T-shirts, pencil skirts, tiered mini dresses, winter wool jackets, summer culottes, off-shoulder dresses, faux leather pants, cropped hoodies, graphic sweatshirts, distressed denim skirts, wrap tops, wide-leg jeans, thermal jackets",
"Women's cropped sweatshirts, zip-up hoodies, faux leather jackets, floral mini skirts, skinny pants, ruffled tops, cable knit sweaters, basic T-shirts, A-line skirts, boho maxi dresses, winter puffer vests, summer linen pants, off-shoulder blouses, leather skirts, oversized sweaters, graphic print T-shirts, denim jackets, wrap dresses, jogger pants, thermal leggings",
"Women's fleece-lined pullovers, thermal sweatshirts, trench coats, floral midi dresses, high-waisted shorts, printed blouses, wool cardigans, striped long-sleeve T-shirts, pencil pants, tiered maxi dresses, winter parkas, summer wide-leg pants, off-shoulder tops, faux leather skirts, cropped hoodies, graphic sweatshirts, distressed jeans, wrap skirts, jogger shorts, thermal tops",
]


# 栏目标题
lanmu_biaoti_set = ["Limited Time Offer","Hot Deals","Best-Selling Products","Flash Sale","Hot Picks","Exclusive Discounts","Unbeatable Prices","Mega Sale","Trending Now","Shop the Hottest Deals","Big Discounts","Best Offers of the Season","Don't Miss Out!","Daily Specials","Special Offers","Summer Sale","Popular Discounts","Special Sale Rush","Exclusive Supply","New Arrivals","Spend and Save Event","Holiday Promotion","Members' Exclusive","Midnight Flash Sale","Time-Limited Purchase","Group Buying Deals","First Order Discount","Free Gifts Galore","Points Redemption","Cash Red Envelopes","Coupon Distribution","Cash Back Shopping","Time-Limited Price Drop","End of Season Clearance","New Users Exclusive","Loyalty Rewards","Daily Time-Limited Specials","Hot Brand Discounts","Consumption Voucher Distribution","Additional Time-Limited Offers","Influencer Recommended","Massive Rush to Buy","Low Price Promotion","High Cost-Performance Ratio","Time-Limited Free Trial","Discount Bundle","Cross-Store Joint Promotion","Early Bird Discounts","Pre-Sale Special Offers","Value Package"]

# 顶部告示语
dingbugoushiyu_set = ["30-day worry-free returns, full refund.",
"Quality issues, free exchange or return within 30 days.",
"No reason needed for refunds within 30 days, worry-free shopping.",
"Defects guaranteed for 30 days, free return shipping.",
"Quality assurance, full refund within 30 days.",
"Quality issues within 30 days, burden-free returns.",
"Stress-free exchanges and returns within 30 days, shop with confidence.",
"Quality issues, free return shipping within 30 days.",
"30-day refund guarantee, worry-free shopping.",
"Quality issues within 30 days, we cover shipping.",
"No reason returns within 30 days, easier shopping.",
"Quality issues, worry-free refunds within 30 days.",
"30-day worry-free exchanges and returns, shop with peace of mind.",
"30-day worry-free returns, shop with confidence.",
"Quality guarantee, commitment to full refund within 30 days.",
"Quality issues within 30 days, pressure-free returns.",
"30-day exchange and return guarantee, worry-free shopping.",
"Quality issues, full refund for returns within 30 days.",
"30-day worry-free exchanges and returns, easier shopping.",
"Size mismatch quality issues within 30 days, free exchange.",
"Unsatisfied quality issues within 30 days, return without worries.",
"30-day after-sales protection, shop with confidence.",
"Damaged packaging within 30 days, free replacement.",
"30-day quality issues worry-free exchange, enjoy stress-free shopping.",
"Missing accessories within 30 days, worry-free reissue.",
"30-day quality guarantee, return if not satisfied.",
"Functional failure within 30 days, free repair or replacement.",
"Quick refund quality issues within 30 days, simple and fast process.",
"Price drop within 30 days, price difference protection.",
"Free trial quality issues for 30 days, return if not satisfied.",
"Damaged items within 30 days, free repair or replacement.",
"30-day extended after-sales, worry-free shopping.",
"Dislike quality issues within 30 days, easy return.",
"30-day worry-free exchange, perfect shopping experience.",
"Item description mismatch quality issues within 30 days, unconditional return.",
"Return shipping subsidy within 30 days, worry-free returns.",
"Lost items within 30 days, full refund.",
"Quick response within 30 days, worry-free after-sales.",
"Damaged items within 30 days, free exchange or return.",
"30-day worry-free exchange, more convenient shopping.",
"Item mismatch within 30 days, easy return.",
"30-day quality commitment, return if not satisfied.",
"Item issues within 30 days, free exchange or return.",
"30-day after-sales guarantee, worry-free shopping.",
"Damaged items within 30 days, worry-free exchange or return.",
"30-day exchange and return guarantee, more confident shopping.",
"Item issues within 30 days, worry-free returns.",
"30-day worry-free returns, more secure shopping.",
"Damaged items within 30 days, full refund.",
"Free return shipping within 30 days, worry-free returns.",
"Item mismatch within 30 days, full refund.",
"Quick exchange within 30 days, worry-free shopping.",
"Item issues within 30 days, worry-free exchange or return.",
"30-day exchange and return guarantee, more convenient shopping.",
"30-day worry-free exchange, more confident shopping.",
"Item issues within 30 days, full refund.",
"Color mismatch quality issues within 30 days, change as you wish.",
"Enjoy 30-day worry-free returns, full refund.",
"30-day no-questions-asked returns, full refund guaranteed.",
"Shop with confidence, easy returns within 30 days.",
"30-day return guarantee, full refund.",
"Satisfaction or your money back, 30-day returns.",
"30-day worry-free returns, no hassle refunds.",
"Your satisfaction is our promise: 30-day worry-free returns.",
"30-day return guarantee, full refund guaranteed.",
"Worry-free returns within 30 days, full refund.",
"Shop stress-free, return within 30 days for a full refund.",
"Worry-free returns: 30-day full refund.",
"Not satisfied? Return within 30 days, full refund guaranteed.",
"30-day full refund protection, shop with confidence.",
"No worries: 30-day returns with full refund.",
"30-day hassle-free returns, guaranteed refund.",
"Shop confidently, 30-day returns with full refund.",
"30-day worry-free returns, easy refunds.",
"30-day no-hassle returns, full refund guaranteed.",
"30-day return protection, full refund.",
"Worry-free shopping, 30-day returns, full refund.",
"30-day worry-free return policy, full refund.",
"Shop confidently, 30-day return guarantee, full refund.",
"30-day no-hassle returns, guaranteed refund.",
"30-day return policy, 100% refund.",
"Worry-free shopping, 30-day returns guaranteed.",
"Not happy? Return within 30 days, full refund.",
"30-day return guarantee, easy refunds.",
"30-day worry-free returns, full refund protection.",
"Worry-free shopping, 30-day return with full refund.",
"30-day no-questions-asked returns, 100% refund.",
"30-day return policy, full refund guarantee.",
"30-day worry-free returns, shopping made easy.",
"Full refund, 30-day worry-free returns.",
"30-day return guarantee, no questions asked.",
"Shop stress-free: 30-day returns, full refund.",
"Return within 30 days, get a full refund.",
"30-day return protection, no hassle refunds.",
"30-day worry-free return policy, full refund guarantee.",
"30-day no-questions-asked returns, guaranteed refund.",
"30-day return guarantee, 100% money back.",
"30-day return policy, no worries, full refund.",
"30-day worry-free returns, refund guaranteed.",
"30-day return assurance, full refund.",
"Full refund guarantee, return within 30 days.",
"No worries: 30-day return policy with refund.",
"30-day worry-free returns, easy full refunds.",
"Shop with peace of mind: 30-day return, full refund.",
"Full refund guarantee with 30-day no-questions-asked return.",
"30-day worry-free returns, hassle-free refund.",
"30-day return protection, full refund guarantee.",
"No worry returns: 30-day full refund.",
"Worry-free returns: 30 days, full refund guarantee.",
"30-day no-hassle returns, full refund guarantee.",
"30-day full refund protection, easy returns.",
"30-day return guarantee, worry-free refund.",
"30-day worry-free returns, full refund policy.",
"No worries: 30-day returns with refund guarantee.",
"Return with ease, 30-day no-hassle returns.",
"Full refund assurance, 30-day returns.",
"Shop confidently: 30-day worry-free returns, refund guaranteed.",
"30-day worry-free return policy, shopping made easy.",
"30-day return protection, easy refund process.",
"Return within 30 days, full refund guaranteed.",
"Full refund guarantee, 30-day returns with ease.",
"Worry-free shopping: 30-day returns with full refund.",
"No worries, 30-day return and full refund policy.",
"Shop without stress: 30-day returns, full refund.",
"30-day worry-free returns, fast refund.",
"Shop with confidence, 30-day return protection.",
"Full refund guarantee with 30-day return policy.",
"30-day worry-free returns, easy shopping.",
"Worry-free returns, 30 days, full refund guarantee.",
"30-day return policy, full refund for all purchases.",
"30-day returns, full refund guaranteed.",
"30-day return protection, get a full refund.",
"30-day worry-free returns, easy refund process.",
"30-day full refund guarantee, shop confidently.",
"30-day returns, no hassle, full refund.",
"Shop confidently, 30-day returns, full refund policy.",
"30-day no-questions-asked returns, easy refunds.",
"30-day worry-free returns, fast and easy refunds.",
"30-day full refund protection, no worries.",
"No hassle returns: 30-day full refund.",
"30-day worry-free returns, shopping without stress.",
"Full refund policy with 30-day returns.",
"30-day return policy, guaranteed full refund.",
"Shop worry-free: 30-day returns, full refund.",
"30-day worry-free return guarantee, full refund.",
"Return with ease, 30-day full refund guarantee.",
"Worry-free returns: 30-day return, refund guaranteed.",
"30-day full refund policy, return anytime within 30 days.",
"Enjoy 30 days of hassle-free returns, full refund.",
"Return within 30 days for a full refund, no questions asked.",
"Shop confidently with 30-day returns and a full refund.",
"No worries, 30-day returns and full refund guaranteed.",
"30-day return policy, worry-free and full refund.",
"30-day no-hassle returns, guaranteed full refund.",
"Full refund within 30 days, shop with peace of mind.",
"30-day worry-free returns, get your full refund.",
"30 days of peace of mind with free returns and full refund.",
"30-day returns made easy, full refund guaranteed.",
"Shop risk-free with 30-day returns and full refund.",
"Full refund within 30 days, no stress shopping.",
"30-day return policy, full refund without hassle.",
"Worry-free returns: full refund, 30 days to decide.",
"30-day returns, full refund, no questions asked.",
"30 days to return for a full refund, completely worry-free.",
"30-day worry-free returns, your full refund is guaranteed.",
"Return it within 30 days for a full refund, no hassle.",
"Full refund guaranteed with 30-day worry-free returns.",
"Full refund with no worries: 30-day return policy.",
"Shop without worries, 30-day returns, full refund.",
"30-day easy returns with a full refund.",
"Enjoy shopping with 30-day return policy, full refund.",
"30-day return guarantee, no questions, full refund.",
"No hassle, 30-day returns with full refund.",
"Full refund for 30-day returns, guaranteed.",
"30-day return guarantee, full refund protection.",
"Worry-free shopping with 30-day returns and full refund.",
"30-day full refund policy, shop with confidence.",
"30-day returns for peace of mind, full refund guaranteed.",
"30-day return option, full refund no matter what.",
"Full refund if returned within 30 days, no hassle.",
"No worries: 30-day returns and full refund guaranteed.",
"30 days to change your mind with a full refund.",
"30-day no-hassle returns, worry-free shopping.",
"Worry-free shopping with 30-day full refund.",
"30-day full refund, return hassle-free.",
"Shop risk-free, return in 30 days for a full refund.",
"30 days to decide, full refund, no questions.",
"Full refund, 30-day no-hassle returns.",
"30-day return protection, full refund guaranteed.",
"30-day worry-free return option, full refund.",
"Full refund with 30-day return protection.",
"30-day easy returns, full refund policy.",
"Shop stress-free, 30-day return policy, full refund.",
"30-day worry-free returns, guaranteed refund.",
"Return it within 30 days, get a full refund, no worries.",
"Shop with peace of mind: 30-day returns, full refund.",
"30-day return window, full refund guarantee.",
"30-day no-questions-asked return policy, full refund.",
"30-day return policy with full refund guarantee.",
"Shop with confidence: 30-day returns, full refund.",
"Full refund guaranteed with 30-day no-hassle returns.",
"30-day no-worry returns, your full refund awaits.",
"Full refund guarantee, 30-day return period.",
"Return within 30 days for a full refund, worry-free.",
"30 days of worry-free returns, full refund.",
"30-day return guarantee, full refund assured.",
"Full refund within 30 days, no hassle.",
"30-day return guarantee, enjoy full refund.",
"30-day return option, full refund, no stress.",
"Full refund for returns within 30 days, guaranteed.",
"Return it within 30 days for a full refund, guaranteed.",
"Full refund, 30-day no-stress returns.",
"30-day worry-free returns, guaranteed full refund.",
"30 days to change your mind, full refund.",
"No questions asked: 30-day return, full refund.",
"30-day returns with a full refund guarantee.",
"Full refund within 30 days, no hassle returns.",
"30-day return window, full refund policy.",
"No worries: 30-day return window, full refund.",
"Return within 30 days, get a full refund, guaranteed.",
"30-day full refund policy, no hassle returns.",
"30-day returns, full refund with no questions.",
"Full refund guarantee, 30-day worry-free returns.",
"30-day full refund protection, return with ease.",
"30-day return policy, guaranteed refund.",
"30 days of worry-free returns, guaranteed refund.",
"Return your item within 30 days for a full refund.",
"Full refund within 30 days, no stress return.",
"Return it within 30 days, full refund guaranteed.",
"30-day returns, full refund, no hassle.",
"30-day return period, full refund guaranteed.",
"Full refund, no questions asked, 30-day return policy.",
"Return within 30 days for a full refund.",
"30 days to return for a full refund, no questions.",
"Full refund guarantee, 30-day return window.",
"No worries: 30-day returns, full refund.",
"30-day return guarantee, get your full refund.",
"30-day worry-free returns, full refund guaranteed.",
"30-day return period, full refund assured.",
"30 days to decide, full refund guaranteed.",
"No hassle returns: 30-day full refund policy.",
"Full refund within 30 days, return with ease.",
"30-day return protection, no questions asked.",
"Full refund guaranteed with 30-day return window.",
"30-day return option, full refund, no worries.",
"30 days of worry-free shopping with full refund.",
"Full refund guarantee, 30-day return policy.",
"30-day returns, full refund, no worries.",
"30-day full refund protection, return with confidence.",
"Return it within 30 days for a full refund.",
"Full refund policy, 30-day return option.",
"Worry-free shopping: 30-day returns, full refund.",
"Shop risk-free, 30-day returns, full refund.",
"No stress: 30-day returns, full refund guaranteed.",
"30-day return guarantee, full refund policy.",
"Full refund within 30 days, no hassle return.",
"30-day worry-free return window, full refund.",
"30-day return guarantee, no hassle refund.",
"Return within 30 days, get your full refund.",
"Shop confidently, 30-day returns, full refund.",
"Full refund with 30-day no-hassle return policy.",
"Worry-free shopping with 30-day returns, full refund.",
"30-day returns, full refund guaranteed, no hassle.",
"30-day no-stress returns, full refund.",
"No questions asked, 30-day return window, full refund.",
"30-day return period, full refund.",
"Full refund guaranteed, 30-day return protection.",
"30-day full refund protection, no hassle returns.",
"Full refund guarantee with 30-day return period.",
"No stress, 30-day return policy, full refund.",
"30-day return option, full refund protection.",
"Full refund for returns within 30 days, no questions.",
"30-day return protection, full refund, worry-free.",
"No questions asked, 30-day returns, full refund.",
"Enjoy 30 days of worry-free returns, full refund.",
"Shop with confidence, 30-day return policy, full refund.",
"Worry-free returns: 30 days to decide, full refund.",
"30-day full refund guarantee, no hassle returns.",
"Full refund if returned within 30 days, no questions asked.",
"30-day returns, guaranteed full refund.",
"Full refund protection for 30-day returns.",
"Shop with peace of mind, 30-day return policy.",
"30 days of worry-free shopping, full refund guaranteed.",
"Return with ease: 30-day full refund guarantee.",
"Full refund within 30 days, no stress return policy.",
"30-day return policy, no questions asked, full refund.",
"30-day full refund guarantee, return with confidence.",
"No hassle, 30-day returns, full refund.",
"Full refund for 30-day returns, no questions asked.",
"30-day return policy, full refund protection.",
"30-day return window, full refund, no questions.",
"Full refund guaranteed with 30-day return policy.",
"Full refund with 30-day no-hassle returns.",
"30-day return window, return with confidence, full refund.",
"30-day return protection, full refund assured.",
"No questions asked: 30-day returns, full refund guaranteed.",
"30-day returns with full refund, no stress.",
"Full refund, return within 30 days, no hassle.",
"30-day return policy, shop with confidence.",
"30-day full refund protection, worry-free shopping.",
"Return it in 30 days, full refund, no worries.",
"30-day returns with full refund policy, no questions asked.",
"Full refund guaranteed for returns within 30 days.",
"Return it within 30 days, get a full refund.",
"Full refund for 30-day returns, no hassle.",
"30-day return policy, full refund assurance.",
"No stress: 30-day return policy, full refund.",
"Worry-free returns with 30-day full refund.",
"30-day full refund, return it anytime.",
"Full refund within 30 days, no questions asked.",
"Return it within 30 days, full refund.",
"Shop with confidence: 30-day return policy, full refund.",
"Full refund protection with 30-day return policy.",
"30-day returns with full refund protection, no worries.",
"30-day worry-free return policy, full refund assured.",
"Full refund for 30-day returns, no questions.",
"Shop risk-free: 30-day returns, full refund.",
"Full refund, 30-day return guarantee.",
"30-day return window, full refund guaranteed.",
"No questions asked, 30-day return policy, full refund.",
"Full refund for returns within 30 days, no hassle.",
"30-day returns, full refund, no worries at all.",
"30-day return protection, full refund policy.",
"30-day return option, full refund no questions asked.",
"30-day worry-free return window, full refund guaranteed.",
"No questions, 30-day returns, full refund.",
"30-day return window, full refund, shop worry-free.",
"30-day return guarantee, no hassle, full refund.",
"Return within 30 days for a full refund, guaranteed.",
"Shop worry-free, 30-day returns, full refund.",
"30-day return policy, no hassle, full refund.",
"Full refund guaranteed, return within 30 days.",
"30-day return policy, full refund, no worries.",
"Full refund for 30-day returns, no hassle, guaranteed.",
"Return it anytime within 30 days, full refund.",
"Shop stress-free with 30-day returns and full refund.",
"30-day return period, full refund policy, no hassle.",
"Shop confidently with 30-day returns, full refund.",
"Full refund policy, 30-day return option, no stress.",
"Full refund, 30-day return policy with no questions.",
"Full refund protection with 30-day return guarantee.",
"30-day return policy with full refund assurance.",
"Return within 30 days for full refund, guaranteed.",
"30-day return guarantee, no hassle refunds.",
"Return within 30 days for a full refund, no hassle.",
"30-day return period, full refund, shop confidently.",
"Shop worry-free: 30-day return policy, full refund.",
"30-day return policy, return with confidence, full refund.",
"Full refund within 30 days, return policy guaranteed.",
"30-day worry-free return policy, get a full refund.",
"Full refund for 30-day returns, guaranteed satisfaction.",
"30-day return policy, no hassle full refund.",
"Full refund guaranteed for 30-day returns, no questions.",
"30-day full refund, return policy without stress.",
"Full refund, 30-day return period, no questions asked.",
"30-day worry-free returns, full refund with ease.",
"Full refund protection with 30-day returns.",
"30-day returns, full refund guarantee with no worries.",
"30-day return guarantee, worry-free shopping.",
"30-day returns with full refund policy, guaranteed.",
"Return it within 30 days for a full refund, worry-free.",
"Full refund within 30 days, no questions asked, no hassle.",
"30-day return policy, full refund, no problem.",
"Return with ease: 30-day full refund protection.",
"Full refund guarantee for returns within 30 days.",
"Return it anytime within 30 days for full refund.",
"Shop confidently with 30-day returns, full refund policy.",
"Return it in 30 days, get a full refund, no worries.",
"30-day worry-free return guarantee, full refund policy.",
"Full refund protection for 30-day returns, guaranteed.",
"Return with confidence, 30-day full refund guarantee.",
"Full refund, 30-day return policy with no stress.",
"30-day return policy, easy returns, full refund.",
"Shop with ease: 30-day returns and full refund.",
"Full refund guaranteed, 30-day worry-free returns.",
"30-day return period, full refund with no hassle.",
"Full refund, 30-day returns with confidence.",
"30-day return window, full refund without hassle.",
"Full refund for 30-day returns, no questions, no stress.",
"30-day return policy, full refund without questions.",
"30-day return protection, easy full refunds.",
"Full refund for 30-day returns, worry-free shopping.",
"Worry-free returns: Decide within 30 days, full refund.",
"Full refund, return within 30 days, no questions asked.",
"Full refund protection, 30-day returns.",
"Return within 30 days, full refund.",
"30-day full refund guarantee, shop with confidence.",
"30-day return guarantee, no questions full refund.",
"Return it in 30 days for a full refund.",
"Full refund, return within 30 days, guaranteed.",
"Worry-free: 30-day return policy, full refund.",
"30-day return period, full refund, no worries.",
"30-day return option, full refund, no questions asked.",
"Enjoy hassle-free returns within 30 days, full refund guaranteed.",
"30-day return window, no questions asked, full refund.",
"Full refund with 30-day return option, no worries.",
"Full refund on all 30-day returns, guaranteed.",
"30-day returns with full refund, no questions.",
"Full refund, worry-free returns within 30 days.",
"Full refund, 30-day returns with no questions asked.",
"30-day return policy, full refund guaranteed.",
"Return within 30 days, get your full refund with ease.",
"30-day returns, full refund with no issues.",
"Enjoy 30-day returns with full refund guarantee.",
"Return for any reason within 30 days, full refund.",
"Shop confidently with 30-day return policy, full refund.",
"30-day return protection, full refund within 30 days.",
"Full refund guaranteed for 30-day returns, no questions asked.",
"Return it anytime within 30 days for a full refund.",
"30-day returns available, full refund guaranteed.",
"Full refund for 30-day returns, shop worry-free.",
"30-day return window, guaranteed full refund.",
"Full refund on 30-day returns, no hassle.",
"30-day return policy, return it, full refund guaranteed.",
"Full refund guaranteed with 30-day return period.",
"30-day return option, full refund with no hassle.",
"Full refund protection, 30-day worry-free return window.",
"30-day return protection, no questions full refund.",
"Full refund for 30-day returns, no questions required.",
"Return it anytime within 30 days for full refund, no questions.",
"Full refund, 30-day return window with no hassle.",
"30-day returns, full refund, no problem.",
"Full refund for returns within 30 days, no stress.",
"Shop with ease: 30-day return policy, full refund.",
"Return it within 30 days for a full refund, hassle-free.",
"Shop worry-free with our 30-day return guarantee.",
"30-day return policy, full refund, no questions asked.",
"Return it within 30 days, guaranteed full refund.",
"30-day returns, full refund without hassle.",
"Full refund guaranteed for all 30-day returns.",
"Return within 30 days, full refund guaranteed, no questions.",
"Shop confidently with our 30-day return, full refund policy.",
"30-day return period, full refund protection.",
"Shop risk-free: 30-day return policy, full refund guarantee.",
"30-day return protection, easy full refund.",
"Return it within 30 days, full refund no questions asked.",
"Full refund on all returns within 30 days, guaranteed.",
"Return it anytime within 30 days, full refund assured.",
"30-day return period, full refund without questions.",
"Full refund guaranteed on all 30-day returns.",
"30-day return guarantee, full refund, no questions.",
"Full refund, 30-day return policy, no stress.",
"Return it within 30 days, full refund assured.",
"Enjoy a 30-day return window, full refund guaranteed.",
"Return within 30 days, full refund, guaranteed satisfaction.",
"Full refund guarantee on all 30-day returns.",
"Full refund for 30-day returns, no questions, no hassle.",
"Return within 30 days for full refund, no questions asked.",
"30-day return period, full refund protection, no hassle.",
"Full refund guaranteed on 30-day returns.",
"Full refund within 30 days, return it stress-free.",
"30-day return option, full refund, guaranteed.",
"Full refund for 30-day returns, no questions, no worries.",
"30-day return window, full refund protection.",
"Full refund, 30-day return protection.",
"Return it anytime within 30 days, full refund policy.",
"30-day return window, full refund, no questions asked.",
"Full refund on 30-day returns, shop with confidence.",
"Return it in 30 days for a full refund, guaranteed.",
"30-day return period, full refund, no questions.",
"Full refund, 30-day return policy, no stress at all.",
"30-day return protection, return it for full refund.",
"Full refund protection, 30-day return window.",
"Return it in 30 days, full refund assured.",
"Full refund on returns within 30 days, no stress.",
"30-day return guarantee, no worries, full refund.",
"Shop worry-free with 30-day returns, full refund.",
"Full refund, 30-day return protection, shop with ease.",
"30-day return window, full refund, no problem.",
"Return within 30 days for a full refund, no stress.",
"Full refund, 30-day return period, guaranteed.",
"30-day return protection, full refund without hassle.",
"Return it anytime within 30 days, full refund protection.",
"Full refund guaranteed with 30-day return protection.",
"30-day return period, full refund, no questions asked.",
"Full refund for returns within 30 days, no problem.",
"Full refund on all returns within 30 days.",
"Shop with ease: 30-day return, full refund.",
"30-day return guarantee, full refund, no hassle.",
"Return it in 30 days for full refund, no questions.",
"Full refund, 30-day return policy, no hassle.",
"Enjoy peace of mind with 30-day returns, full refund guarantee.",
"Shop confidently with 30-day returns, full refund protection.",
"30-day return policy, full refund, no hassle required.",
"Full refund within 30 days, worry-free shopping.",
"30-day returns, full refund, guaranteed satisfaction.",
"Shop risk-free: 30-day return window, full refund.",
"Full refund guarantee on 30-day returns.",
"30-day full refund guarantee, worry-free returns.",
"Return it within 30 days, full refund, guaranteed.",
"30-day return protection, no questions, full refund.",
"30-day return option, full refund without hassle.",
"Return anytime within 30 days for a full refund.",
"30-day return policy, full refund guaranteed, no questions.",
"Full refund for 30-day returns, no stress, no worries.",
"Return it within 30 days for full refund, no questions asked.",
"Shop stress-free with 30-day return, full refund.",
"30-day return period, full refund guarantee, no questions.",
"Full refund, no hassle with 30-day returns.",
"Return within 30 days, get your full refund, no issues.",
"30-day return window, full refund, guaranteed satisfaction.",
"Shop worry-free with 30-day return policy, full refund.",
"Full refund, 30-day return protection, no questions.",
"30-day return policy, no questions, full refund guarantee.",
"Shop confidently with 30-day returns, full refund guarantee.",
"Full refund on 30-day returns, no questions asked.",
"30-day return window, full refund, no stress.",
"Shop without worries: 30-day return policy, full refund.",
"30-day return guarantee, full refund, easy process.",
"Full refund for returns within 30 days, guaranteed protection.",
"Shop confidently, 30-day return policy, full refund guarantee.",
"30-day return protection, full refund, no questions asked.",
"Full refund on returns within 30 days, no hassle.",
"30-day return policy, easy full refund process.",
"30-day return protection, full refund without questions.",
"Full refund, 30-day returns, no questions.",
"Return it within 30 days, full refund, no stress.",
"Full refund for 30-day returns, no issues.",
"Return anytime within 30 days, full refund assured.",
"Full refund, 30-day return guarantee, worry-free.",
"30-day return protection, full refund with ease.",
"Shop risk-free: 30-day return policy, full refund.",
"Full refund guarantee, 30-day return protection.",
"30-day returns, full refund, no questions, no worries.",
"Return within 30 days for full refund, guaranteed protection.",
"Shop stress-free with 30-day return policy, full refund.",
"Full refund protection, 30-day return policy.",
"30-day return window, full refund, no hassle.",
"30-day return period, full refund, guaranteed.",
"Return within 30 days, full refund, no problem.",
"30-day return policy, full refund, guaranteed.",
"30-day returns, full refund, no questions needed.",
"Full refund, 30-day return protection, no hassle.",
"30-day return option, full refund guarantee, no worries.",
"Full refund protection, 30-day return period.",
"Return within 30 days, full refund, no worries.",
"30-day return window, full refund, guaranteed protection.",
"Shop with ease, 30-day return policy, full refund.",
"Return within 30 days, full refund, no questions required.",
"30-day return guarantee, full refund assured, no questions.",
"Shop confidently, 30-day return policy, full refund protection.",
"30-day return policy, full refund, no problems.",
"Full refund on all 30-day returns, no hassle.",
"Full refund protection for returns within 30 days.",
"30-day return policy, full refund, no stress at all.",
"30-day return policy, full refund, return with confidence.",
"Full refund on 30-day returns, no questions, guaranteed.",
"Shop worry-free: 30-day returns, full refund guarantee.",
"Full refund for 30-day returns, no questions, guaranteed.",
"30-day return period, full refund, return with confidence.",
"Full refund, 30-day return policy, no questions.",
"30-day return protection, full refund without worry.",
"Full refund guaranteed, 30-day return policy.",
"30-day return guarantee, full refund protection, no worries.",
"30-day return guarantee, full refund, no questions required.",
"30-day return policy, return it anytime for full refund.",
"Full refund protection, 30-day return guarantee.",
"30-day return policy, full refund, worry-free shopping.",
"30-day return guarantee, no hassle, full refund protection.",
"Full refund on returns within 30 days, guaranteed.",
"Full refund for 30-day returns, guaranteed protection.",
"30-day return policy, full refund, no questions.",
"Return it anytime within 30 days for a full refund, no hassle.",
"30-day worry-free returns, full refund guarantee.",
"Return it in 30 days for full refund, guaranteed protection.",
"30-day return policy, full refund, guaranteed protection.",
"Full refund on 30-day returns, guaranteed satisfaction.",
"30-day return policy, full refund guarantee, no questions.",
"Return within 30 days, full refund without questions.",
"Full refund, 30-day return policy, return with ease.",
"30-day return guarantee, full refund, no stress at all.",
"Full refund for 30-day returns, no worries.",
"Full refund, 30-day return policy, guaranteed protection.",
"Enjoy easy returns with our 30-day full refund guarantee.",
"Shop worry-free: 30-day return guarantee, full refund.",
"Full refund for returns within 30 days, guaranteed satisfaction.",
"Return it in 30 days for a full refund, no questions asked.",
"30-day return window, full refund protection, no stress.",
"30-day return guarantee, return with peace of mind, full refund.",
"Full refund, 30-day worry-free return period.",
"30-day return option, full refund with ease.",
"Return within 30 days for a full refund, no worries.",
"30-day return policy, full refund guarantee, no hassle.",
"Return within 30 days for full refund, worry-free.",
"30-day return protection, full refund, guaranteed.",
"30-day return period, no questions asked, full refund.",
"Full refund guaranteed for 30-day returns.",
"Full refund on 30-day returns, no stress.",
"30-day return policy, full refund with no questions.",
"Full refund, no hassle, 30-day return policy.",
"Return it within 30 days for full refund, guaranteed.",
"30-day return protection, full refund, no stress.",
"Full refund on returns within 30 days, no problem.",
"30-day return guarantee, full refund, no questions asked.",
"30-day return policy, full refund, no hassle.",
"Return it within 30 days, full refund with ease.",
"30-day return period, full refund, no issues.",
"Return it within 30 days, get a full refund, no issues.",
"30-day return guarantee, full refund, worry-free.",
"30-day return policy, no stress, full refund.",
"Full refund, 30-day return protection, guaranteed.",
"Full refund on all 30-day returns, no questions.",
"Return it within 30 days, full refund, guaranteed protection.",
"30-day return guarantee, full refund, no stress.",
"Return it in 30 days for full refund, guaranteed.",
"30-day return period, full refund, worry-free.",
"Full refund for 30-day returns, no problem.",
"Shop confidently: 30-day returns, full refund.",
"30-day return guarantee, full refund without questions.",
"Full refund for 30-day returns, no worries at all.",
"Return it within 30 days for full refund, no questions.",
"30-day return window, full refund, no worries.",
"30-day return policy, full refund, easy returns.",
"Return within 30 days, full refund, no issues.",
"30-day return period, full refund, guaranteed protection.",
"Full refund for 30-day returns, no questions needed.",
"30-day return window, full refund protection, no hassle.",
"Full refund on all 30-day returns, no problem.",
"Return it in 30 days for a full refund, no stress.",
"Full refund protection, 30-day return window, no hassle.",
"30-day return guarantee, full refund, shop with confidence.",
"30-day return option, full refund guarantee.",
"Full refund on 30-day returns, worry-free shopping.",
"30-day return policy, full refund, guaranteed satisfaction.",
"Full refund, 30-day return guarantee, no hassle.",
"Return it within 30 days for a full refund, no issues.",
"30-day worry-free return period, full refund.",
"Full refund protection for all returns within 30 days.",
"Shop with peace of mind, 30-day return, full refund.",
"Return it within 30 days for full refund, no hassle.",
"30-day return option, full refund protection, no worries.",
"30-day return guarantee, full refund, guaranteed protection.",
"Return it in 30 days for full refund, no stress.",
"30-day return window, full refund, easy return.",
"Shop confidently, 30-day return policy, full refund.",
"30-day return protection, full refund, no problem.",
"Full refund protection, 30-day return period, no stress."]

# 商品详情 shop now
shop_now_set =["Shop Now!","Buy Now!","Get Yours Now!","Order Today!","Grab Yours!","Shop Today!","Limited Time Offer!","Don't Miss Out!","Add to Cart!","Shop Online!","Start Shopping!","Get It Now!","Shop & Save!","Act Now!","Shop the Sale!","Hurry, Shop Now!","Buy It Today!","Take Advantage!","Shop and Enjoy!","Hurry, Limited Stock!","Order Now!","Find Your Deal!","Best Prices Now!","Check Out Now!","Unlock Your Deal!","Hot Deal Alert!","Special Offer Today!","Limited Stock Available!","Shop the Collection!","Grab the Deal!","Save Big Now!","Don't Wait, Shop Now!","Claim Your Offer!","Buy Now, Pay Later!","Exclusive Deal!","Hurry, Offer Ends Soon!","Today Only!","Treat Yourself Today!","Act Fast!","Get It While It Lasts!","Snap Up the Deal!","Shop the Best Deals!","Sale Ends Soon!","Shop Now, Save More!","Ready to Shop?","The Best Deals Await!","Unlock the Savings!","Browse and Buy!","Shop the Discount!","Instant Savings!","Your Deal is Waiting!","Take the Deal!","Only a Few Left!","Shop & Earn Rewards!","Save More, Shop More!","New Arrivals – Shop Now!","Shop with Us Today!","Shop & Get Free Shipping!","Enjoy the Savings!","Shop the Sale Event!","Grab the Latest Deals!","Flash Sale Today!","Buy and Save!","Don't Miss This Offer!","Hurry Up & Shop!","Order & Save Today!","Get Started Now!","Hot Prices – Shop Now!","Buy Before It’s Gone!","Fast Delivery – Shop Now!","Sale On Now!","Take the Offer!","Instant Discounts Available!","Last Chance to Shop!","Click to Shop!","Best Offers Here!","Shop for Less!","Start Saving Now!","Find Your Perfect Item!","Exclusive Offers Inside!","Only a Few Left – Shop Now!","Order & Get a Free Gift!","Shop for Big Savings!","Shop and Enjoy Free Gifts!","Limited Time Savings!","Discounted Prices Now!","Don't Miss the Sale!","Shop & Get More for Less!","Your Favorite Products Are Here!","Shop Smart, Save Big!","Shop & Get Rewarded!","Get It While It's Hot!","Shop the New Collection!","Big Sale on Now!","Flash Deal – Shop Now!","Save While You Shop!","Exclusive Discounts Available!","Last Call for Deals!","Check Out Today!","Treat Yourself Now!","Best Deals Are Waiting!"]


# 模板 模块 对应关系
muban_mokuai = {
    "1":"ad-grid-1",
    "2":"ad-grid-1",
    "3":"ad-grid-1",
    "4":"ad-grid-1",
    "5":"ad-grid-1",
    "6":"ad-grid-1",
    "7":"ad-grid-1",
    "8":"ad-grid-1",
    "9":"ad-grid-1",
    "10":"ad-grid-1",
    "11":"ad-grid-1",
    "12":"ad-grid-1",
    "13":"ad-grid-1",
    "14":"ad-card-1,ad-card-2,ad-card-1,ad-card-3",
    "15":"ad-card-4,ad-card-1,ad-card-2,ad-card-4,ad-card-1,ad-card-3,ad-card-1,ad-card-2",
    "16":"ad-grid-2-1-2,ad-card-4,ad-card-3",
    "17":"ad-grid-1half-2-2,ad-grid-2-2-1half,ad-card-4,ad-card-4",
    "18":"ad-grid-1-1,ad-card-1,ad-grid-1-1-1,ad-card-4",
    "19":"ad-grid-1-2,ad-card-1,ad-grid-1,ad-card-4",
    "20":"ad-card-4,sp4,ad-card-3,ad-card-4",
    "21":"ad-grid-1-1-1,sp4,ad-card-3",
    "22":"ad-card-4,ad-card-1,sp8",
    "23":"sp8,ad-card-1,ad-card-3,sp8",
    "24":"ad-grid-1half-2-2,sp8,ad-card-1,ad-grid-2-1half-2,ad-card-1,ad-grid-2-2-1half,ad-card-3",
    "25":"ad-card-3,sp8,ad-card-1,ad-card-2",
    "26":"ad-grid-1,ad-card-2,ad-card-2,ad-card-4,ad-card-3",
    "27":"ad-card-1,ad-grid-1,ad-grid-1,sp8,ad-card-3",
    "28":"ad-card-4,sp8,ad-card-3,ad-card-4",
    "29":"ad-grid-1-1,sp4,ad-grid-1-1,ad-card-1,sp4",
    "30":"sp8,ad-card-1,ad-card-2,ad-card-3,ad-card-1",
    "31":"ad-card-4,ad-card-2,sp8,ad-card-3,ad-card-1,ad-grid-1",
    "32":"sp8,ad-card-1,ad-card-1,ad-card-1,ad-card-3",
    "33":"ad-grid-1,sp8,ad-card-1,ad-card-3,ad-card-3",
    "34":"ad-card-3,sp8,ad-card-1,ad-card-3,ad-card-1",
    "35":"ad-card-4,ad-card-1,sp8,ad-card-1,ad-card-3",
    "36":"ad-card-4,ad-grid-1,sp8,ad-card-1,ad-card-3",
    "37":"ad-card-4,ad-card-2,ad-grid-1,sp8,ad-card-1,ad-card-3",
    "38":"ad-card-4,ad-card-3,sp8,ad-card-1,ad-grid-1,ad-card-3",
    "39":"ad-card-4,sp8,ad-card-1,ad-card-2",
    "40":"ad-grid-1,ad-card-1,sp8,ad-card-1,ad-card-4",
    "41":"ad-card-2,sp8,ad-card-1,ad-card-3"
}

# 生成美国电话
def generate_us_phone_number():
    r"""
    # 示例调用
    random_phone = generate_us_phone_number()
    print(random_phone)
    """
    # 随机生成区号（3位数字，避免以0开头）
    area_code = random.randint(200, 999)

    # 随机生成电话号的前3位
    first_part = random.randint(100, 999)

    # 随机生成电话号的后4位
    second_part = random.randint(1000, 9999)

    # 组合成电话号码格式
    phone_number = f"+1 ({area_code}) {first_part}-{second_part}"
    return phone_number



# 列表随机元素
def suiji_yuansu(my_list,n):
    r"""
    s = suiji_yuansu(my_list=lanmu_biaoti,n=3)
    print(s)  # ['Consumption Voucher Distribution', 'Best-Selling Products', 'Mega Sale']
    """
    import random
    if n > len(my_list):
        raise ValueError("选择的元素数量不能大于列表的长度")
    # my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    # 从列表中随机选择5个不重复的元素
    random_elements = random.sample(my_list, n)
    # print(random_elements)
    return random_elements

# 随机一个
def suiji_one(my_list):
    return suiji_yuansu(my_list=my_list, n=1)[0]

# 获取本地所有文件
def get_all_file(path):
    f_l=[]
    for dirpath, dirnames, filenames in os.walk(path):
        for filename in filenames:
            # print(os.path.join(dirpath, filename))  # 这是没有排序的
            f=os.path.join(dirpath, filename)
            f_l.append(f)
    return f_l

# 读取本地json文件数据
import json

# json文件数据
def load_image_path_mapping(file_path="web_path.json"):
    r"""
    file_path="web_path.json"
    data = load_image_path_mapping(file_path)
    pic_web_path = data.get(image_path)
    """
    # 尝试读取 JSON 文件并返回映射字典
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data
    except (FileNotFoundError, json.JSONDecodeError):
        # 如果文件不存在或者文件格式有误，返回一个空字典
        print("文件未找到或格式错误。")
        return {}

# 获取网络路径图片
def get_pic_web_path(image_path, file_path="web_path.json"):
    r"""
    # 示例调用
    image_path = "path/to/your/image.png"
    pic_web_path = get_pic_web_path(image_path)
    """
    # 读取映射字典
    data = load_image_path_mapping(file_path)

    # 查找本地路径对应的网络路径
    pic_web_path = data.get(image_path)

    if pic_web_path:
        print(f"本地路径 {image_path} 对应的网络路径是: {pic_web_path}")
        return pic_web_path
    else:
        print(f"未找到 {image_path} 对应的网络路径。")
        return None

# input_file = r"C:\Users\Administrator\Desktop\10000.txt"
# with open(input_file, 'w') as f:
#     for i in range(100000):
#         s = generate_us_phone_number()
#         f.write(s)
#         f.write("\n")

shop_now_set = [
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
','.join(suiji_yuansu(guanjianci_set,n=12)),
]